### ISSUE TITLE
codalabworker image request bug

### ISSUE THREAD

**Issue by EntilZha** [codalab/codalab-worksheets#1005]
We spent some time to get a worker running for our competition at University of Maryland (https://pinafore.github.io/qanta-leaderboard/) and in the process believe we've found a bug in how images are pulled. Specifically:
1) If there is no tag in the image, and cl attempts to pull an image by hash, it fails
2) A minor issue on arguments to pull

Since the worker code isn't on github I pulled the tarball from https://pypi.org/project/codalabworker/ for 0.2.38. For reference we have our students use our image `entilzha/quizbowl` and we debugged with `entilzha/quizbowl@sha256:3a1cb49fc0c65e91100ef9e435030c43c444297685e595b738b15c3b83f46d8c`

Our issue occurred when we:
1) Submitted a job with a custom image, but with no tag (such as latest or an explicit version)
2) Attempted to rerun this job with mimic, which means it should use the image hash
3) This resulted in an error like `Unable to download Docker image: 400 Client Error: Bad Request ("invalid reference format")`
4) So we tried to manually pull this image with `docker pull` which succeeded.

At this point its useful to reference the `docker_client.py` file which is part of the codalabworker code: https://gist.github.com/EntilZha/a3c781601da87ec72974b3a50319c0e8

So we tried running this and it succeeded:
```python
docker_client = DockerClient()
docker_client._client.pull('entilzha/quizbowl', 'sha256:3a1cb49fc0c65e91100ef9e435030c43c444297685e595b738b15c3b83f46d8c')

```
While this failed:
```python
>>> from docker_client import DockerClient
>>> client = DockerClient()
>>> p = lambda x: True
>>> client.download_image('entilzha/quizbowl@sha256:3a1cb49fc0c65e91100ef9e435030c43c444297685e595b738b15c3b83f46d8c', lambda x: True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "docker_client.py", line 19, in wrapper
    raise DockerException(message + ': ' + str(e))
docker_client.DockerException: Unable to download Docker image: 400 Client Error: Bad Request ("invalid reference format")
```

With this in mind I believe there is a bug on line 222 https://gist.github.com/EntilZha/a3c781601da87ec72974b3a50319c0e8#file-docker_client-py-L222

For situation (1)
If `docker_image` is `entilzha/quizbowl@sha256:3a1cb49fc0c65e91100ef9e435030c43c444297685e595b738b15c3b83f46d8c` then `repo` is `entilzha/quizbowl@sha256` and `tag` is `3a1cb49fc0c65e91100ef9e435030c43c444297685e595b738b15c3b83f46d8c`. Since the former is an invalid image format it fails as we observed.

For situation (2)
if `docker_image` is `entilzha/quizbowl:1.0@sha256:3a1cb49fc0c65e91100ef9e435030c43c444297685e595b738b15c3b83f46d8c` (note tag), then there will be a tuple unpack error since there are three values (a ValueError). This gets caught by the except statement which then sets the `repo` to `entilzha/quizbowl:1.0@sha256:3a1cb49fc0c65e91100ef9e435030c43c444297685e595b738b15c3b83f46d8c` and `tag` to `latest`. Fortunately it seems that the docker library ignores the tag argument if its specified in the `repo` so no real issue there. IE, these are equivalent in behavior. Since we have only one version for our image the example below uses ubuntu instead
```python
from docker_client import DockerClient
client = DockerClient()
client._client.pull('ubuntu:16.04@sha256:e547ecaba7d078800c358082088e6cc710c3affd1b975601792ec701c80cdd39')
# {"status":"Pulling from library/ubuntu","id":"sha256:e547ecaba7d078800c358082088e6cc710c3affd1b975601792ec701c80cdd39"}
client._client.pull('ubuntu:16.04@sha256:e547ecaba7d078800c358082088e6cc710c3affd1b975601792ec701c80cdd39', tag='latest')
# {"status":"Pulling from library/ubuntu","id":"sha256:e547ecaba7d078800c358082088e6cc710c3affd1b975601792ec701c80cdd39"}
client._client.pull('ubuntu:16.04', tag='sha256:e547ecaba7d078800c358082088e6cc710c3affd1b975601792ec701c80cdd39')
# {"status":"Pulling from library/ubuntu","id":"sha256:e547ecaba7d078800c358082088e6cc710c3affd1b975601792ec701c80cdd39"}
client._client.pull('ubuntu', tag='sha256:e547ecaba7d078800c358082088e6cc710c3affd1b975601792ec701c80cdd39')
# {"status":"Pulling from library/ubuntu","id":"sha256:e547ecaba7d078800c358082088e6cc710c3affd1b975601792ec701c80cdd39"}
```
We were able to fix this issue by modifying the code to this to handle the case of no version tag, but having an image hash:
```python
        try:
            if '@sha256' in docker_image:
                repo, tag = docker_image.split('@')
            else:
                repo, tag = docker_image.split(':')
```
If this looks correct, it would be great to get this into the pypi version at some point. Thanks!

**Comment by bkgoksel** [comment]
Hello,

First of all thank you so much for this really detailed bug report and solution!

The issue and solution all look valid to me, however we recently merged a change that largely rewrites a lot of our Docker logic, so the `DockerClient` class doesn't exist anymore and we use the official Docker Python SDK to interact with docker, and a lot of this code was rewritten in that change.

These changes haven't been released yet as we're still preparing to upgrade our production machines, but you can find the worker code on our master branch in the GitHub repo at:
https://github.com/codalab/codalab-cli/tree/master/worker/codalabworker 

The docker functionality is now divided between:
https://github.com/codalab/codalab-cli/tree/master/worker/codalabworker/docker_utils.py
(this is a functional module  that wraps some docker API calls to mount volumes to containers etc)
and
https://github.com/codalab/codalab-cli/blob/master/worker/codalabworker/local_run/docker_image_manager.py
(this is a stateful object that manages the docker image cache, pulling and removing images as needed)

The relevant functionality to this issue is in the `get()` function of the `DockerImageManager` (lines 128-129):
```
    image = self._docker.images.get(image_spec)
    digest = image.attrs.get('RepoDigests', [image_spec])[0]
```
Where the `images.get` function is the [method from the Docker-Python SDK](https://docker-py.readthedocs.io/en/stable/images.html#docker.models.images.ImageCollection.get)

Since we let the DockerPY SDK handle the name resolution for docker images now, I think this issue should be fixed on master now. Let me know if you think there might still be issues.

As for a release, we're planning to release this version of our worker within a week, so you could just wait for that, or just run workers off the master branch. Closing this issue now as hopefully it's already fixed :)

Thanks again for your help, and let us know if you run into any issues!
