### ISSUE TITLE
'cl help' does not work on web terminal 

### ISSUE THREAD

**Issue by ChengshuLi** [codalab/codalab-worksheets#103]
it gives me:
```
CodaLab CLI version 0.1.3
'server'
```
rather than a list of commands.

**Comment by andreweduffy** [comment]
Also am seeing this.

**Comment by andreweduffy** [comment]
@ChengshuLi This is because @klopyrev moved the `server` command into `codalab/bin/cl.py` from `codalab/lib/bundle_cli.py`. Because the django app's `general_command` function creates a `BundleCLI` directly, when it builds the help information it doesn't find the help info for `server`, so then it throws the exception.
