### ISSUE TITLE
Slurm Worker: set remote properly

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1036]
Instead of setting to codalab.stanford.edu, use the actual machine.

**Comment by bkgoksel** [comment]
Turns out this is not so simple to do either. The `remote` field is actually set server-side as the hostname of whatever machine is acting as the worker. To allow the worker to freely set the remote we'd need to change this logic and have the worker report the `remote` for its runs, which is not super difficult, but just adds another system-wide API change into the mix.

**Comment by bkgoksel** [comment]
And also this means I need to figure out how to get the hostname of our workers from within the workers which I don't know how to do at the moment.
