### ISSUE TITLE
i detach a bundle, how to rm it forver? 

### ISSUE THREAD

**Issue by w0nche0l** [codalab/codalab-worksheets#1093]
_From @Jasperty on March 3, 2019 1:31_

_Copied from original issue: codalab/codalab-worksheets#486_

**Comment by bkgoksel** [comment]
As per our docs, the `cl rm <bundle_spec>` removes the bundle identified by the spec.
The spec can be:
* the bundle UUID
* `<host-worksheet>//<bundle-name>`
* `^<idx>` where `<idx>` is the number the bundle is from the bottom of the worksheet (ie the last bundle would be '^1', second to last bundle would be `^2` etc

In your case since you detached, the best bet would be `cl rm <BUNDLE UUID>`.
