### ISSUE TITLE
Support parallel worksheet mutation

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#1122]
From Jesse:

"When you (1) open a worksheet for editing, (2) submit a bunch of jobs via the command line, (3) edit the worksheet and save the worksheet, the jobs you added to the worksheet are eliminated (and left dangling). Maybe make sure the worksheet hasn't been changed (e.g. new bundles) since you opened the worksheet?"

**Comment by percyliang** [comment]
In general, need better handling when multiple edits happen on a worksheet simultaneously.  The frontend should try to use patch opterations as much as possible so that edits are localized, which shouldn't interfere with edits elsewhere in the worksheet (CLI just appends).

**Comment by epicfaace** [comment]
This isn't a problem anymore, because 1) the `/add-items` endpoint doesn't affect the rest of the worksheet and is called when editing a single worksheet block and 2) when making multiple bundles from the web CLI, the bundles are added to the worksheet before you can actually focus back on the worksheet
