### ISSUE TITLE
Make loading worksheets asynchronous

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1234]
Currently, the entire worksheet (including fetching all information of all bundles) has to be loaded before anything renders (including the title of the worksheet).  Should instead get the worksheet and then asynchronously load all the parts of the worksheet.  This will require refactoring some backend APIs.

We should split the /interpret request into two request:
- get worksheet info and items
- get bundle_infos that are used for each item (i.e. which are rendered in the table)

**Comment by epicfaace** [comment]
Meeting notes from 4/2/2020:
- outstanding issue with focusIndex - raw_to_block, block_to_raw, items (we should try to use another way to handle focuses; work with @yipenghe  to discuss this, because this will affect copy/paste of bundles)
- we should also add a change to make files load asynchronously
