### ISSUE TITLE
Contiguous blocks of text appear on the same line

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#1268]
- Click "TEXT" and add a single text block.
- Click "TEXT" again and add another text block.
- When you save the second block, both text blocks get "merged" instead of being separate blocks on separate lines, as expected.

![image](https://user-images.githubusercontent.com/1689183/60401870-5b15a900-9b3c-11e9-8e19-173f317835b7.png)

**Comment by percyliang** [comment]
Agree this is surprising.  To make the second text block actually separate, we would need to add a newline to each text block (which is mildly weird).  The problem is that we don't have a native representation of text blocks - they are derived by looking at the list of raw worksheet line items and merging lines according to some logic.  We should just think through this a bit more carefully.
