### ISSUE TITLE
add monitor.py to codalab_service.py

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#1280]

**Comment by candicegjing** [comment]
Some questions about this ticket:
1. When do we want to start the monitoring script? Do we want to start it in the same time as rest-server service? Or do we want it to be run in the same way as test_cli.py?
2. Since monitor.py keeps running a while loop forever, do we want it to continuously send back monitoring status? When I tested calling monitor.py from codalab_service.py, somehow all the log messages were blocked to show up in the caller process until it got killed manually. So I am want to  confirm its right behavior here. 
3. Where do we want to place the monitoring log file? Since container is stateless, I guess it might not be a good idea to store it there. Then another option would be somewhere in the local machine?

**Comment by percyliang** [comment]
1) It shouldn't be started by default (which is local dev).  But if you do `-s monitor` then it should start it.
2) It should continue to run continuously in a loop and emails once in a while.  So we should make sure the email part is configured properly.
3) By default, it can just be in the container, but you can add a flag (like how `codalab_home` and `bundle_stores` are handled).

**Comment by candicegjing** [comment]
For 3, my understanding is that if we output logs to container, we won't be able to retrieve it, as container is stateless.

**Comment by percyliang** [comment]
You can still retrieve it while the container is running (`docker logs`).  This is probably fine for now actually so don't even worry about the flag.  The main purpose of the monitor script is to send out the emails anyway.
