### ISSUE TITLE
Accessing bundle UUID from within a run?

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#1301]
Hi!

Is it possible to access a bundle's UUID from _within the bundle, while it's running_? A (slightly contrived) example: say I'm training a model, and I'd like to save the weights and include a link to the bundle somewhere. Another use case: I don't know if anyone has tried to do notifications for codalab runs, but it could be useful if you want to programmatically send an email to someone when a run fails, where said email is sent within the run and includes a link to the run's bundle in the web interface.

**Describe the solution you'd like**
Perhaps the bundle UUID is written to an environment variable of some sort? Not sure how it works behind the scenes, so this could just be impossible---sorry if that's the case.

**Comment by percyliang** [comment]
This is a good question.  For performing the computation, a run bundle shouldn't need the uuid, so it'd be nice if we didn't need it.  To better explore the use cases:
- For notifications, we have intentions to support email notifications when particular jobs fail or complete.  - For the link to the bundle, suppose the bundle writes a file with the uuid in it; but in order to send a link to that file, you would need the uuid anyway?

In the meantime, the secret is that the current directory is the uuid, so if you really need it, you can get it.

**Comment by nelson-liu** [comment]
Great, thanks!
