### ISSUE TITLE
User Question: Managing secrets in CodaLab?

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#1302]
Hi!

Another possibly bizarre question, sorry. Are there any recommendations for how to use secrets / sensitive data in CodaLab (e.g., API keys)? The transparency of CodaLab (a good thing!) does seem to make this a bit tricky, since the world has read access to the underlying bundle(s) anyway...

**Comment by nelson-liu** [comment]
Follow-up: I managed to limit the scope of a token I was using such that I'm no longer worried if it's exposed publicly. Feel free to close this issue, but maybe it warrants an answer for future users.

**Comment by percyliang** [comment]
Hmm...in general, things that require network access isn't ideal from a strict reproducibility point of view, so at the highest level, if there's a way to call the API with a bunch of queries and cache them to a static file, upload the bundle as a file, then you can just use CodaLab sans secrets.

If it's not possible to do that (because you need to make adaptive queries), then you can start a run that expects the API key to be fed in later (and not stored in the bundle).  `cl write` and `cl netcat` provide ways to communicate with a running process.

Yet another way is to start a temporary server outside CodaLab that has the API key and just forwards your requests along.  Then your CodaLab jobs can talk to this server, and you can shutdown the server when you're done.
