### ISSUE TITLE
[USER ISSUE] Out of time quota

### ISSUE THREAD

**Issue by ajoshi80** [codalab/codalab-worksheets#1490]
**Describe the bug**
Seeing this issue when starting runs or uploading tasks: UsageError: Out of time quota: 73d23h / 60d0h (123.3%)

I'm working with Pranav Rajpurkar on the CheXpert Competition
**Codalab Information**
- User name : anirudhjoshi
- *UUID of worksheet where problem occurred*: 0xf38cc8163bc947848b3289ba6059f183
- *UUID of problem bundle (please don't delete)*:
- *Error message received from Codalab (if applicable)*:UsageError: Out of time quota: 73d23h / 60d0h (123.3%)
 - *OS (if on CLI)*: macOS
 - *Codalab CLI Version (if on CLI)*: 
 - *Browser (if on Web)*;

**To Reproduce**
Steps to reproduce the behavior :

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ajoshi80** [comment]
I'm working with Pranav Rajpurkar on the CheXpert Competition

**Comment by yipenghe** [comment]
Time quota increased, let me know if there is any problem, thanks!

**Comment by ajoshi80** [comment]
Could I also preemptively request for more space quota. I'm working with a large dataset and I'm sure I will run out of space soon/.

**Comment by yipenghe** [comment]
> Could I also preemptively request for more space quota. I'm working with a large dataset and I'm sure I will run out of space soon/.

Hi, for disk request, can you fill out this form? Thanks
https://docs.google.com/forms/d/e/1FAIpQLSdS22MaLyE1kx0JL-w2a8f8IasDyc36H_ZuidNBVAE_afMCpw/viewform

**Comment by gaotianyu1350** [comment]
Hi guys, I am also running out of time quota. I do not need a large time quote for each run (basically within 2 days), but since I am holding an evaluation of a dataset, I run a lot of bundles recently so the time quota is not enough now (for now it is 5d / 7d). I wonder if there is a policy to help the short-but-frequent-run users like me.

By the way, my account is `gaotianyu1350`. Thanks!
