### ISSUE TITLE
make "ls" list files in a bundle instead of in the worksheet

### ISSUE THREAD

**Issue by tachim** [codalab/codalab-worksheets#15]
There's unexpected behavior where
- calling cat on a bundle with multiple files will list the files
- calling cat on a bundle with one file will actually print the entire file

To keep things consistent with the unix semantics of cat and ls we should
1. have cat only print files and throw an error if it's called on a non-file (e.g. a folder bundle)
2. have ls list the contents of bundles instead of worksheets, since we already have print for the latter

If you guys think this is a reasonable idea I can make a pull request

**Comment by percyliang** [comment]
The reason for having 'cat' (although unorthodox) is that it's easy to type 'cl cat' and then just append to the path as you traverse the path.  This is more convenient than having to change the command.

cl print is not a replacement for cl ls since the former could hide bundles.  If you want to reference bundles via '^', then cl ls is safer.

I think we should keep things the way they are.
