### ISSUE TITLE
The value of available memory fetching from each worker is off.

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1577]
The following memory is from `vm-clws-dev-worker-0`. 
```
azureuser@vm-clws-dev-worker-0:~$ free -b
              total        used        free      shared  buff/cache   available
Mem:    14683045888   696700928  2286202880   143355904 11700142080 13081202688
Swap:             0           0           0
```
If we check the value from `WorkerInfoAccessor.user_owned_workers()`, we got the following :
```
[{'user_id': '0', 'worker_id': 'vm-clws-dev-worker-0', 'tag': None, 'cpus': 4, 'gpus': 0, 'memory_bytes': 14683045888, 'free_disk_bytes': 185502568448,...}]
```
So the memory_bytes from the service is using the `total memory` instead of the `available memory`.

**Comment by bkgoksel** [comment]
I think this was an intentional design of the worker system to take the total memory and subtract the bundles' memory usage server-side. I'm guessing this is because we want to "reserve" the entire memory request of a bundle for that bundle, even if it is not using all of it at the time.

So let's say a worker has 4g of memory, and already has a bundle that requested 3g of memory running on it. However, that bundle just started and is only using 1g of memory at the moment. The worker would report having 3g of available memory and we might then schedule a bundle with 2g memory requested to that worker, breaking our contract with the bundles.

**Comment by candicegjing** [comment]
@bkgoksel I see. That's good to know. I guess what I was thinking is that before our worker container starts on a host machine, its memory might have already been taken by some other processes, for instance, a docker daemon. Then we still cannot fully use the `total memory`. 
But I guess if we never had issue related to this memory allocation before (meaning there is no over usage of memory computing resources), we can close this ticket for now.
