### ISSUE TITLE
[USER ISSUE] Can not run my own worker

### ISSUE THREAD

**Issue by pengshuang** [codalab/codalab-worksheets#1582]
**Describe the bug**
I follow the official document to run my own worker, but I find that it didn't work on my worker (I have installed Docker).

**To Reproduce**
Steps to reproduce the behavior :
 1. pip install codalab
 2. cl-worker --verbose
 3. cl run date --tag ps

**Screenshots**
![屏幕快照 2019-10-31 下午8 43 13](https://user-images.githubusercontent.com/11802795/67947658-15b6d480-fc1f-11e9-912d-888707a34915.png)

**Comment by candicegjing** [comment]
The steps to run your personal workers are documented at [running your own worker](https://codalab-worksheets.readthedocs.io/en/latest/Execution/#running-your-own-worker).
Based on the steps you provided above, when you start your personal worker, you can change the `verbose` to be `--tag <worker_tag>`. 
Then the full command becomes:
```cl-worker --tag <worker_tag> ```
Next, in your step 3, you can assign your jobs to the worker you just created by the following command:
```cl run date --request-queue tag=<worker_tag>```
Feel free to let us know if you run into other problems.

**Comment by entslscheia** [comment]
> The steps to run your personal workers are documented at [running your own worker](https://codalab-worksheets.readthedocs.io/en/latest/Execution/#running-your-own-worker).
> Based on the steps you provided above, when you start your personal worker, you can change the `verbose` to be `--tag <worker_tag>`.
> Then the full command becomes:
> `cl-worker --tag <worker_tag> `
> Next, in your step 3, you can assign your jobs to the worker you just created by the following command:
> `cl run date --request-queue tag=<worker_tag>`
> Feel free to let us know if you run into other problems.

Hi, according to the official guide (i.e., the link you provided), by doing:
`cl-worker --verbose`
`cl run date`
We should see that `date` command is running on our own local worker as described in _'You should see that the run finished, and if you look at the remote metadata field, you should see your hostname.'_
However, after running my own worker by executing `cl-worker --verbose` (I got the same output as the above screenshot so I guess it was successful) and executing `cl run date`, I checked the metadata and found it was not really running on my local machine.
So do we need to use `tags` to precisely assign a bundle to a specific worker? Is the original guide incorrect (since it doesn't work for me)?
Any suggestion would be greatly appreciated!
