### ISSUE TITLE
What to do with bundles that are requested with more computing resource than we have in system?

### ISSUE THREAD

**Issue by candicegjing** [codalab/codalab-worksheets#1587]
This is more of a general question to handle those bundles that were requested with more computing resources than we currently have in the system. For example, some bundles were requested to use 2 GPUs. For this kind, do we want to keep them in `staged` state or kill them right away? Killing them seems to be a better option as they won't be able to run anyway.

**Comment by bkgoksel** [comment]
This came up before as well. I think the reason we don't want to kill them right away is that a user might be planning to launch a worker for that bundle after submitting the bundle. Especially with the current state of Worker Managers for deployments like Slurm or AWS Batch, that will be the way things run.

A better solution would be to fail staged bundles that stay staged longer for some period of time (and maybe making that timeout parameter configurable by an argument of the `cl run` command or something).

We already have a similar logic for transitioning `running` bundles into `worker_offline` after a timeout. We could probably add something similar to move `staged` or `worker_offline` bundles to `failed` if time since last state change is > some threshold.

**Comment by candicegjing** [comment]
@bkgoksel I see. I guess my next question is once a user submitted a bundle, how can he reassign this bundle to run on a worker he brings up later? 
The reason I asked is that I think those jobs will slow down the process of assigning workers to bundles on the current scheduling system.

**Comment by bkgoksel** [comment]
This happens automatically. As soon as there's a worker that can run a bundle, the bundle manager schedules it there. I think having a few extra bundles shouldn't be too bad, especially after we fix the resource double counting bug.
