### ISSUE TITLE
cl wedit -f ...

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#185]
Saving a worksheet on the CLI makes a ton of calls to get_bundle_uuids (to the same bundle, in fact), which makes things really slow.  None of these calls should be made.  Seems like a bug.

**Comment by kashizui** [comment]
I'm not able to reproduce multiple calls to `get_bundle_uuids` on the same bundle, what does your worksheet look like?

I do see a call to `get_bundle_uuids` for each entry on the worksheet, and unfortunately that's necessary at the moment since each call may raise a `UsageError` in `canonicalize`, which we want to catch on an individual basis in order to put the error messages on the matching lines in the worksheet.

We can refactor this but it would not be a quick fix.

**Comment by percyliang** [comment]
I just have one worksheet with 100 copies of the same bundle.
When wedit saves, I see 100 calls to the server.

**Comment by kashizui** [comment]
Understood—
OK, we will need to batch the calls to `get_bundle_uuids` from `worksheet_util.parse_worksheet_form`, while still allowing for a per-bundle resolution of errors.

We may also want to do some caching on the `LocalBundleClient` side to save work when resolving multiple references to the same bundle, currently each bundle_spec will cause a call to canonicalize.

(^notes to self but open for comment)

**Comment by kashizui** [comment]
Yes, `codalab/apps/web/bundles.py:233` relies on this function. I'll make sure that there are no new issues.

**Comment by kashizui** [comment]
Fixed in #218
