### ISSUE TITLE
[Bug] Failing to evaluate model - unexplained error

### ISSUE THREAD

**Issue by ofersabo** [codalab/codalab-worksheets#1923]
Hi,

Username: ofersa
- *UUID of the worksheet where the problem occurred*: couldn't find
UUID of problem bundle: 0xeb1d96

Used CLI on a linux OS
CLI version 0.5.4

**To Reproduce**
Steps to reproduce the behavior :
1. Go to my worksheet, run-predict uuid 0xeb1d96
2. Click on 'edit and rerun'
3. wait for the process to end 

**Expected behavior**
I expect the process to generate a prediction file. The prediction file is a list of numbers.
I expect no error as in my local machine. 

**Screenshots**
attached is a screenshot from the worksheet sidebar, which states that the process is killed.
![error](https://user-images.githubusercontent.com/31179968/72986936-fe3c5180-3df1-11ea-91b7-dfa2537d1dd7.png)

**Additional context**

Recently, I have been working to submit my trained model's prediction on a competition test set.
I created my own docker to mimic my local environment.

The program's first step is downloading a pre-trained model from a server. To this end, I ask a codalab server with a network connection. This enables the process to successfully download the model, but just after that, the process fails.

The stderr file doesn't hold any information regarding the failure reason.
I don't see any way to debug this failure, I note that in my local machine the program runs smoothly.

**Comment by yipenghe** [comment]
How large is your pretrained model? Might need a disk quota increase https://docs.google.com/forms/d/1z_-XTz79_dPg7fe859Sde0xGNtvaoyv2PzTdeIAAJhM/

**Comment by ofersabo** [comment]
The model requires 1.2 GB, as far as I see my remaining disk quota is more than 5GB.  
I doubt if this is indeed the issue, but I would double-check it.

**Comment by ofersabo** [comment]
I filled out the form to ask for a larger quota a week ago but still couldn't get access to a larger size quota. 
Any other suggestions?

**Comment by yipenghe** [comment]
> I filled out the form to ask for a larger quota a week ago but still couldn't get access to a larger size quota.
> Any other suggestions?

Processed your disk request, sorry for the delay, thought it was processed by last oncall. Can you try your submission again?

**Comment by ofersabo** [comment]
Hi @yipenghe ,

I just retried it after getting the larger quota, It still generates the same output and same result. 
Could you look into it? 

the process UUID:
0xf58431

**Comment by yipenghe** [comment]
> Hi @yipenghe ,
> 
> I just retried it after getting the larger quota, It still generates the same output and same result.
> Could you look into it?
> 
> the process UUID:
> 0xf58431

I took a look and tried a rerun, I noticed you only requested 4g memory and 1 cpu, I think your code might need more than 4g memory at the same time to keep it running. I reran it by requesting more memory and got the stderr:

`
Traceback (most recent call last):
  File "predictor_debuger.py", line 58, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/predict.py", line 227, in _predict
    manager.run()
  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/predict.py", line 205, in run
    for batch_json in lazy_groups_of(self._get_json_data(), self._batch_size):
  File "/usr/local/lib/python3.6/site-packages/allennlp/common/util.py", line 104, in <lambda>
    return iter(lambda: list(islice(iterator, 0, group_size)), [])
  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/predict.py", line 182, in _get_json_data
    input_file = cached_path(self._input_file)
  File "/usr/local/lib/python3.6/site-packages/allennlp/common/file_utils.py", line 106, in cached_path
    raise FileNotFoundError("file {} not found".format(url_or_filename))
FileNotFoundError: file input.json not found
`

which was not in the original run. Since this looks a like run time error, you can probably go from here.

Request more memory should no longer get the 'killed' error

**Comment by ofersabo** [comment]
Many Thanks @yipenghe 
This issue is resolved now.

I do have a different issue now, but since it is unrelated I would open a new issue.
