### ISSUE TITLE
[USER ISSUE] cl run sometimes creates floating bundles

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2051]
**Describe the bug**

I have a script with loop that runs some `cl run` command on ~120 bundles. The last few output run bundles produced from this loop are consistently floating (i.e., they're not being properly added to the current worksheet returned by `cl st`). I can try to come up with a minimal reproducible example, but thought that I'd raise this issue in the meantime in case anyone has a clue of why this might be happening...

**To Reproduce**
1. `cl run` many bundles in quick succession.

**Expected behavior**
All bundles are appended to the current worksheet

**Actual behavior**
Some bundles are properly appended to the current worksheet, others are not. screenshots to help explain your problem.

**Additional context**
All of these run bundles are very small, taking ~5s each to run (evaluating SQuAD model predictions).

**Comment by candicegjing** [comment]
@nelson-liu Want to confirm with you on the following two details:
1. I want to make sure I understand the issue here, so I wonder what's the `cl st` command you mentioned in your original post?
1. I ran some experiments in my local machine and found out that even without submitting too many bundles, I got floating bundles when I didn't specify `cl work <uuid>` within the script. Once I specified the `cl work <uuid>` inside the script that I tried to submit a bunch of runs, those bundles were able to attach to the worksheet that I specified. So I wonder if you could provide more details on how you ran the script when you discovered this issue.

**Comment by nelson-liu** [comment]
Oops, `cl st` is `cl status`.

Hm, I just ran a custom python script to kick off jobs. It relied on me being "working" on the right codalab worksheet before i ran it, it would be an easy fix to add a `cl work` into it...

**Comment by candicegjing** [comment]
Also, I wonder which library in your script that you were using to submit those bundles?

**Comment by nelson-liu** [comment]
I was using the `subprocess.run` function

**Comment by candicegjing** [comment]
Did you specify `shell=True` when you call `subprocess.run`?

**Comment by nelson-liu** [comment]
Hmm, I don't think I did...but it should have ended up in _some_ bundle,
right (instead of being floating)?

**Comment by candicegjing** [comment]
Yes. They should tie to the current worksheet. Another thing that I want to verify with you is that the floating bundle you were seeing doesn't tie to any worksheet, right? And if you go to your DASHBOARD, do they show up in the `My floating bundles` section if there is any?
The reason I asked this is that my bundles got tied to a different worksheet instead of the one that I wanted to submit to.

**Comment by nelson-liu** [comment]
Yup, they were in that section of the dashboard, which is how i noticed them in the first place.

**Comment by candicegjing** [comment]
I tried 5 times locally submitting 120 bundles that run a simple command to a worksheet. All bundles seem to be able to attach to the worksheet correctly. @nelson-liu In case I missed some important details, could you provide the full script that you were running into this problem?

**Comment by percyliang** [comment]
does `for x in {1..1000}; do cl run date; done` trigger this bug?  @nelson-liu have you had any more problems lately?

**Comment by nelson-liu** [comment]
I think this is related to session management things...I haven't run into this in particular recently, it's fine to close.
