### ISSUE TITLE
Disable merge button on Github PR's where Travis build is failing

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#2077]
- Disable merge button on Github PR's where Travis build is failing
- We should also require at least 1 approval in order to merge.
- We might also want to enforce that remote branches should be updated with master before checking in.

**Comment by teetone** [comment]
We should also require at least 1 approval in order to merge.

**Comment by yipenghe** [comment]
@percyliang Can we enforce this?

**Comment by epicfaace** [comment]
I've just added this. Incidentally, it appears that these very rules were applied to the `release` branch originally, but since we don't appear to be using that branch anymore, I changed it to apply those rules to the `master` branch:

![image](https://user-images.githubusercontent.com/1689183/76685606-7a316980-65eb-11ea-8481-c747e0980c27.png)
