### ISSUE TITLE
Revisit "Running your own worker" documentation

### ISSUE THREAD

**Issue by imirzadeh** [codalab/codalab-worksheets#2109]
**Describe the bug**
Hi, Is there any up-to-date tutorial on how to set-up GPU workers from scratch?    
I could set up the worker with CPU but I couldn't do it with the nvidia-docker.   
I used this repository to setup nvidia-docker: [https://github.com/NVIDIA/nvidia-docker](https://github.com/NVIDIA/nvidia-docker)  and then found out the documentation is working with the legacy version nvidia-docker. Am I missing something?

**Comment by nelson-liu** [comment]
If you can run `docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi` and get the `nvidia-smi` output, then you should be good to go. Just run `cl-worker` and the worker should automatically pick up the gpus (you can set the `--gpuset` flag to be sure).

If not:

CodaLab workers are a bit sketchy with the most recent versions of docker (19.03+, i think), which use the `--gpus` flag to connect GPUs to the containers.  When I tried to set up the worker, it kept complaining about an unknown runtime nvidia. This is because of: https://github.com/codalab/codalab-worksheets/issues/1426

I got around this by:
1. Uninstalling my latest version of Docker
2. Reinstalling an old version of Docker. See https://docs.docker.com/install/linux/docker-ce/ubuntu/ , "To install a specific version of Docker Engine - Community, list the available versions in the repo, then select and install:". I think I used `18.09.9`
3. Follow the `nvidia-docker2` setup instructions at: https://github.com/NVIDIA/nvidia-docker/wiki/Installation-(version-2.0)
4. Test that things work by running:

```
docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
```

**Comment by teetone** [comment]
To revisit and possibly update: https://codalab-worksheets.readthedocs.io/en/latest/Execution/#running-your-own-worker
