### ISSUE TITLE
[USER ISSUE] Bundles on jagupards have incorrect time while running

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2112]
**Describe the bug**

Jobs that run on the jagupards (hosts in the Stanford NLP cluster) have incorrect timestamps while running—the durations are properly calculated when the jobs are finished. For instance, https://worksheets.codalab.org/bundles/0x477a3881d0184d4cbb212ad3c5c5b83f shows that the time is `-1y364d`. I guess there's some time subtraction going on based on what docker reports, and the time zone of the container might differ from codalab's server time?

**To Reproduce**
Steps to reproduce the behavior :
1. Run a bundle on a jagupard machine.

**Expected behavior**

Duration is properly calculated. 

<img width="1560" alt="Screen Shot 2020-03-26 at 1 26 00 PM" src="https://user-images.githubusercontent.com/7272031/77693318-5ebc4c00-6f65-11ea-84c8-dcf6304f63c7.png">

**Comment by nelson-liu** [comment]
Oops, this isn't an issue with `jagupard`s in general...maybe a docker image specific thing? Regardless, it'd bed good to get some guidance on how to get the right time to show up.

**Comment by percyliang** [comment]
@candicegjing you were looking at the time stuff lately, right?

**Comment by candicegjing** [comment]
@percyliang Yes. I'll take care of this. I realized this issue earlier and it seems it only happens in NLP cluster machine, not in our public instances. Also, this timing issue only happens at the beginning of each running bundle. When bundles get refreshed on their run state, the number will be corrected. I'll reply back once I figure out the root cause.
