### ISSUE TITLE
`run_status` : Unexpectedly unable to assign enough resources

### ISSUE THREAD

**Issue by graykode** [codalab/codalab-worksheets#2155]
Job state is `preparing` but not go to `running` and `run_status` is unable resources.

```
Unexpectedly unable to assign enough resources: Requested more CPUs (6) 
than available (3 currently out of 6 on the machine)
```

I try to kill this bundle but change automatically to `preparing` state.

**Comment by candicegjing** [comment]
I am trying to fix this. Will update you once it's done. In the same time, could you please resubmit your bundle?

**Comment by graykode** [comment]
@candicegjing Sure thanks! I've resubmitted the bundle.

**Comment by newstyn** [comment]
Hi @candicegjing I am facing the same issue with a bundle that i uploaded 4 days ago, its still in the preparing state. 
Also there are two more bundles that i uploaded today like  and they are also stuck in the preparing state . 
I am going to give my worksheet name along with bundle id, just in case you needed them
Worksheet: newstyn-EBIC , BundleID: 0xbe8875
Worksheet: newstyn-EBIC , BundleID: 0xd0a166
Worksheet: newstyn-EBIC , BundleID: 0x74461d

I am not sure if i do should resubmit these bundles again because it takes hours and sometimes days even to just get in the preparing state.

**Comment by candicegjing** [comment]
@newstyn Could you please resubmit your bundles? I am trying to fix this as soon as possible. Please note that the long waiting time is due to the high demand in the past few weeks. We have already added more GPU workers and they are all fully occupied now.
