### ISSUE TITLE
Get rid of ._ files when uploading from a Mac

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#2209]
Get rid of `._` files  when using the tar library with `COPYFILE_DISABLE=1`.

**Comment by epicfaace** [comment]
@teetone I realized that I undid this in an earlier Blob Storage PR. Do you think we still need this change though?

**Comment by percyliang** [comment]
It would be nice to keep this change, or else we get a lot of junk files in the bundles when you upload from MacOS.

**Comment by epicfaace** [comment]
Additionally, now thinking about this further, this issue is actually fixed even with the partial revert I did in my PR https://github.com/codalab/codalab-worksheets/pull/3412. This is because --disable-copyfile is still added when bsdtar is available (Macs always have bsdtar), so --disable-copyfile is still added. This means that Macs still ignore ._ patterns when zipping files for upload.
