### ISSUE TITLE
[Code cleanup] A more central call for Ajax calls

### ISSUE THREAD

**Issue by yipenghe** [codalab/codalab-worksheets#2223]
It might better to wrap some ajax call into a function, not sure what a cleaner version would look like, maybe @epicfaace has more thoughts on it?

**Comment by epicfaace** [comment]
@jzwang43 just so you're aware, here's a related issue about refactoring network calls on the frontend: https://github.com/codalab/codalab-worksheets/issues/3307

@yuqijin changed some network calls to use useSWR in https://github.com/codalab/codalab-worksheets/pull/3353, because it nicely acted as a global cache and helped avoid duplicate requests. We might want to look into using useSWR for other use cases, as well, but as a first step, completing this issue would be a prerequisite as we'd probably first want all ajax calls to be called from a central location (#2223).
