### ISSUE TITLE
search_time test fails intermittently in test_cli

### ISSUE THREAD

**Issue by teetone** [codalab/codalab-worksheets#2319]
The `search_time` test module failed for me in a Travis build. After I restarted the build, the test module passed. Below is a screenshot of the failure:

![search_time fails intermittently](https://user-images.githubusercontent.com/16793796/83086460-aafa3a00-a043-11ea-8611-30c992406fce.png)

**Comment by teetone** [comment]
@armantajback Can you take a look at this? It seems like `cl search` by time is returning an unexpected result.

**Comment by epicfaace** [comment]
It might have to do with the fact that the search_time uses `run_command` instead of `_run_command` -- I've fixed this in my github actions PR -- https://github.com/codalab/codalab-worksheets/pull/2185/files#diff-cb8561d21199b20fca8542382a4b4fb6R963

We may want to apply that fix separately in another PR since the github actions PR is held up.
