### ISSUE TITLE
make first run on GitHub Actions not take 10 minutes

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#2388]

**Comment by teetone** [comment]
After taking another look at the GHA logs, it turns out the it takes 6-7 minutes to download the first CodaLab Docker image onto a fresh VM for GHA:

![download_docker_image_GHA](https://user-images.githubusercontent.com/16793796/85093401-09c55600-b1a1-11ea-885c-8acf1665d591.png)

Related:
https://github.community/t/speed-comparison-github-actions-takes-3m-32s-circle-ci-takes-12s/17780

https://github.community/t/slow-docker-image-download-speed-which-is-the-best-place-to-host-docker-images/16189

We are currently down to a 13-15 total build time. @epicfaace @percyliang I'm not sure if there is anything more we can do from our side in regards to the slow image pull.

**Comment by nelson-liu** [comment]
Do the tests have to be run with `codalab/default-cpu:latest`? That's a 5GB image, mostly filled with things that aren't relevant to the tests (e.g., Tensorflow, Scala, Java). Could create a slimmer test worker image and use that (just for the tests).

dockerfile, for reference: https://github.com/codalab/codalab-worksheets/blob/master/docker/dockerfiles/Dockerfile.default-cpu

**Comment by epicfaace** [comment]
@nelson-liu that's a great idea! We could even use something as small as `ubuntu:xenial` for the worker image.
