### ISSUE TITLE
Rethink testing infrastructure

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#2714]
- REST API tests
- Unit test code coverage check in GHA

- multiple users/permissions

**Comment by percyliang** [comment]
Should first start by writing up a document taking stock of our current tests (unit tests, test cli, frontend selenium tests) and describing the various types of things we need to test.  Tests are currently hard to write because we haven't invested in the proper scaffolding to make testing ergonomic.  Things which are particularly challenging: multiple users/permissions, live running workers, etc.
