### ISSUE TITLE
UsageError: {"error": "invalid_grant"}

### ISSUE THREAD

**Issue by nelson-liu** [codalab/codalab-worksheets#2724]
Sometimes, codalab fails to authenticate and returns `UsageError: {"error": "invalid_grant"}` for any command you run. The workaround is to delete your state file (or the auth entry), but it'd be good to fix.

I did some sleuthing, seems like https://github.com/codalab/codalab-worksheets/blob/master/codalab/server/auth.py#L29-L46 is returning a `urllib.error.HTTPError: HTTP Error 400: Bad Request`.

**Comment by teetone** [comment]
It turns out `codalab.stanford.edu` has this commit: https://github.com/codalab/codalab-worksheets/commit/04e3abef87178c03f702a08e875d7a33ecb354b9, which caused login issues, but doesn't have the revert commit: https://github.com/codalab/codalab-worksheets/commit/1f2c0ea6fadc0eaf5e86bc3d5b407c146bf348d4. I will see if this is fixed after patching the instance.

**Comment by teetone** [comment]
Okay, it seems like my hypothesis was correct:

Right before patching the Stanford instance:

![before](https://user-images.githubusercontent.com/16793796/89840046-22f4de00-db24-11ea-8e69-8ad0b7f72250.png)

Right after patching the Stanford instance:

![after](https://user-images.githubusercontent.com/16793796/89840054-26886500-db24-11ea-8be4-08eac94cab91.png)

**Comment by nelson-liu** [comment]
nice! thanks
