### ISSUE TITLE
old DockerHub images not available

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#2801]
https://www.docker.com/blog/scaling-dockers-business-to-serve-millions-more-developers-storage/
Old docker images won't be kept forever, so how do we maintain reproducibility?  Solutions:

1) Maintain our own local docker repository
2) Give up on reproducibility

**Comment by epicfaace** [comment]
For 1., we have two options:
- [Azure Container Registry](https://azure.microsoft.com/en-us/services/container-registry/) (probably more expensive)
- Use an Azure Blob-storage-backed storage driver for a Docker repository -- https://docs.docker.com/registry/storage-drivers/azure/

**Comment by percyliang** [comment]
It would be interesting to pull all the docker images that exist with any bundle and see how many there are and how many are still around and estimate the space usage.

**Comment by nelson-liu** [comment]
(i have a script that will backup docker images for a bundle, given uuids, would be happy to help out with this if i can)

**Comment by percyliang** [comment]
Should use Azure as a backup only.  Would be nice to be able to restore the backup to DockerHub easily.

**Comment by epicfaace** [comment]
This has been delayed until at least mid-2021, so we still have some time before we have to address this: https://www.docker.com/blog/docker-hub-image-retention-policy-delayed-and-subscription-updates/


Also, there's a third option here:
1. Maintain our own local docker repository
2. Give up on reproducibility
3. "Ping" all codalab images on Docker Hub every few months.

I think 3. might actually be pretty viable, and I don't think it's necessarily circumventing any terms of service -- we are "pinging" these images because they are in fact "in use" -- we require them to be available for reproducibility. I'd imagine that only a small minority of our runs use custom, seldom-used / one-time-use Docker Hub images, so it may be acceptable to use the ping solution. (Essentially, the small number of custom images we use may not be a reason for us to move _everything_ over to our own Docker repository.)
