### ISSUE TITLE
save docker image id

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#285]
Currently, the metadata field of a bundle `docker_image` is something like codalab/ubuntu:1.9, which is merely a tag and doesn't pinpoint the exact image.  We should store the image id instead (request_docker_image will be the friendly name).

This requires calling `docker` to lookup the image ID (somehow).

**Comment by a10y** [comment]
So the logical place to do this is inside of remote_machine.py where the docker_image metadata is set. This proves challenging however when the image has never been pulled before. Currently, the way I see getting past this it to either:
1. Preemptively pull the image
2. Leave `docker_image` in the user-supplied `repository[:tag]` format. This will be used in the shell script that runs docker. Docker pulls the image, so it'll be cached locally in the future
3. Overwrite the `docker_image` metadata value elsewhere.

@percyliang which seems the most acceptable? I am not sure what the purpose behind using image id's instead of image names was to begin with: is it due to greater reproducibility? If so then #1/#3 might make the most sense.

**Comment by percyliang** [comment]
On Sat, Dec 26, 2015 at 8:04 PM, Andrew notifications@github.com wrote:

> So the logical place to do this is inside of remote_machine.py where the
> docker_image metadata is set. This proves challenging however when the
> image has never been pulled before. Currently, the way I see getting past
> this it to either:
> 1. Preemptively pull the image
> 2. Leave docker_image in the user-supplied repository[:tag] format.
>    This gets passed to remote_machine, which builds the shell script that runs
>    docker. Docker pulls the image, so it'll be cached locally in the future
> 3. Overwrite the docker_image metadata value elsewhere.
> 
> @percyliang https://github.com/percyliang which seems the most
> acceptable? I am not sure what the purpose behind using image id's instead
> of image names was to begin with: is it due to greater reproducibility? If
> so then #1 https://github.com/codalab/codalab-cli/pull/1/#3
> https://github.com/codalab/codalab-cli/issues/3 might make the most
> sense.
> 
> The rationale is for reproducibility.  Tags change, so if someone puts in
> ubuntu:latest, in 5 years, that will surely point to something else.

Also, note that the docker image gets pulled on the worker machines, not
where remote_machine.py is running.

Is it not possible to get the image id given a tag from dockerhub without
pulling the image?  That's quite suboptimal.

I'd probably do the following: modify the bash script that the worker runs
(created by remote_machine.py) to have it lookup the docker image id and
write it to <uuid>.stats.  Then the remote_machine.py can read that file
and write it to the metadata when the value comes in.  See how the memory
usage gets passed back.

**Comment by a10y** [comment]
@percyliang 

> Is it not possible to get the image id given a tag from dockerhub without
> pulling the image?  That's quite suboptimal.

Currently it's not possible. Right now docker is in a state of flux, seems that in the not-too-distant future they're planning on making SHA256 digests part of the image structure by default so that you can have content-addressable images. This is part of the current structure as of v1.9, but digests are actually only created when you push to a registry, which is a no-no here. Eventually these digests are supposed to replace Image IDs completely, as per [this thread](https://groups.google.com/forum/#!topic/docker-user/PvAcxDrvP30), so we might want to keep that in the back of our mind but for now we can still focus on saving the Image IDs.

> Also, note that the docker image gets pulled on the worker machines, not
> where remote_machine.py is running.

I was under the impression that the `work-manager` is running on the worker machine, is that not the case? Is the work-manager just run by a regular user when they want to track the status of their jobs then?

> I'd probably do the following: modify the bash script that the worker runs
> (created by remote_machine.py) to have it lookup the docker image id and
> write it to <uuid>.stats.  Then the remote_machine.py can read that file
> and write it to the metadata when the value comes in.  See how the memory
> usage gets passed back.

Okay, I'll take a poke at that. I realized that the `q` script seemed to rely on a Linux environment so I setup a dev environment in an Ubuntu VM. I'm having a few issues that I'll ping you about offline.

**Comment by percyliang** [comment]
On Sun, Dec 27, 2015 at 10:59 AM, Andrew notifications@github.com wrote:

> @percyliang https://github.com/percyliang
> 
> Is it not possible to get the image id given a tag from dockerhub without
> pulling the image? That's quite suboptimal.
> 
> Currently it's not possible. Right now docker is in a state of flux, seems
> that in the not-too-distant future they're planning on making SHA256
> digests part of the image structure by default so that you can have
> content-addressable images. This is part of the current structure as of
> v1.9, but digests are actually only created when you push to a registry,
> which is a no-no here. Eventually these digests are supposed to replace
> Image IDs completely, as per this thread
> https://groups.google.com/forum/#!topic/docker-user/PvAcxDrvP30, so we
> might want to keep that in the back of our mind but for now we can still
> focus on saving the Image IDs.
> 
> That's good to know.  In the future, we should keep track of the digests.

Actually, it seems like you can't actually 'docker pull' an image ID (is
that right?), in which case, having the image ID doesn't seem quite as
useful as you'd like...maybe the digests will be pull'able from docker hub?

> Also, note that the docker image gets pulled on the worker machines, not
> where remote_machine.py is running.
> 
> I was under the impression that the work-manager is running on the worker
> machine, is that not the case? Is the work-manager just run by a regular
> user when they want to track the status of their jobs then?

cl work-manager is run on the same machine as cl server and the website.
This is the thing that talks to the database and copies things over to the
worker machines.

**Comment by a10y** [comment]
> Actually, it seems like you can't actually 'docker pull' an image ID (is
> that right?), in which case, having the image ID doesn't seem quite as
> useful as you'd like...maybe the digests will be pull'able from docker hub?

That's correct, it doesn't seem like the registry keeps any information about image IDs, they're mostly just for you to make sure that you're using the same Image. However, as of 1.6 you can pull based on digest, example:

``` bash
> docker pull andreweduffy/kali-metasploit@sha256:17d00988a4190c89617a3a8a859cfc54475a5b1bf00c1c64735b787fa215d859
```

**Comment by percyliang** [comment]
You can use 'docker inspect' to get the digest, but it seems like it's only
if it was originally pulled using the digest:
http://stackoverflow.com/questions/32046334/what%C2%B4s-the-sha256-code-of-a-docker-image

**Comment by a10y** [comment]
So do we still care about saving Image IDs? We can't build automation around them and they're being phased out in the future. Digests are the future but support is not perfect yet

**Comment by percyliang** [comment]
Let's not invest time in supporting image IDs.  Perhaps the best thing to
do is to table this issue and wait until digests are more stable.

**Comment by a10y** [comment]
Sounds good to me, closing this out for now, we'll create a new issue eventually that tracks digest support.
