### ISSUE TITLE
check performance of REST API with Flask

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#301]
Sync with @kashizui on this

**Comment by klopyrev** [comment]
I set up a Flask server that can receive file uploads using the instructions here: http://flask.pocoo.org/docs/0.10/patterns/fileuploads/

I uploaded both a 1GB file and a 4GB from my laptop to my desktop machine over the Stanford network. I measured speeds of 7.29MB/s and 6.94MB/s for the 1 and 4 GB files, respectively.

I transferred the same amount of data using netcat and TCP. I was able to get speeds of 7.96 MB/s and 7.03 Mb/s, for 1 and 4 GBs, respectively.

**Comment by percyliang** [comment]
Can you try this on the NLP machines?  You should get 100Mb/s.

Also, can we get a sense of how speeds degrade as more users connect?

**Comment by klopyrev** [comment]
I did a couple more tests. With Flask and a single upload at a time I can only get 27MB/s, while with netcat I get more than 100MB/s. So, definitely something is off. Trying multiple files sent from different I notice that Flask serializes the uploads so that only a single machine is uploading at a time. Perhaps I've misconfigured the Flask server. I'll keep digging.

**Comment by klopyrev** [comment]
To get Flask to have multiple threads you need to use gunicorn, an alternative server. You tell gunicorn how many worker processes to run, and it starts a different instance of Flask in each process. I guess they use processes, instead of threads, since threading in Python is a bit broken.

Anyway, I can only get about 60 MB/s upload speed when 4 1GB files are being uploaded at a time. I suspect that the reason I can't get more is that the hard drive on the server is slow. I get about 120MB/s sequential write speed on the hard drive. With 4 files being written to different locations that should be significantly less.

**Comment by percyliang** [comment]
Thanks for checking all this stuff out.  If we have 1 1GB file being
uploaded, do you get close to 120MB/s?

**Comment by klopyrev** [comment]
No, I get up to 30MB/s. Not sure why. I'm not sure if it's worth digging into it further, though. It seems that 30 MB/s is pretty fast.

**Comment by klopyrev** [comment]
For what it's worth both Dropbox and Google Drive APIs are REST APIs:

https://www.dropbox.com/developers/documentation/http/documentation
https://developers.google.com/drive/v2/reference/

**Comment by percyliang** [comment]
30MB/s is not a problem for users in a web browser contacting the bundle
service.  However, we were planning to use REST for worker-server
communication, which currently is based on rsync, so going from 100MB/s to
30MB/s is a huge hit.

**Comment by klopyrev** [comment]
I'd like to understand what you're trying to do. Let's talk when you have
time.

Konstantin

**Comment by klopyrev** [comment]
There's some really bad code in one of the libraries used by Flask: Werkzeug.

First, it doesn't do what it says it does. What it says it does is store the data in a temporary file if the size of the file is larger than some limit. What it does instead is always store the entire file in memory, at least in one part of the code.

Second, the code it uses to download the file is totally broken. It constructs a Python str containing the entire file. The way that it does it is by repeatedly constructing and reconstructing an array containing strings of size 65536. Instead of just appending each new such string to the array, it actually constructs a whole new array by iterating over the old one and moving the strings to the new array. The guilty code is here: https://github.com/mitsuhiko/werkzeug/blob/master/werkzeug/wsgi.py#L834

This handling of uploaded files is just silly. I'm having some doubts about the quality of the whole library, given such low quality of the file uploading code.

**Comment by klopyrev** [comment]
There's a bug for the issue here: https://github.com/mitsuhiko/werkzeug/issues/510

**Comment by kashizui** [comment]
Aye that's terrible!

Should we alternatively also look into http://www.django-rest-framework.org/? Perhaps more mature..

(Reading this discussion: https://www.quora.com/What-is-a-good-Python-framework-for-building-a-RESTful-API)

**Comment by percyliang** [comment]
http://klen.github.io/py-frameworks-bench/

Maybe falcon?  Seems much faster than the others.  Lightweight is also good.

**Comment by kashizui** [comment]
Falcon does look pretty slick, and seems to match our needs:
- speed/performance
- lightweight
- agnostic to other components (our serialization layer and models, etc)
- designed for REST APIs

only concern is its low version number, the vague wording of its intended use ("Cloud APIs"), and there doesn't seem to be a mature library for building an OAuth API on falcon yet so we may need to build our own on top of OAuthLib. Worth investigating upload/download speed on?

**Comment by percyliang** [comment]
I think it's worth playing around with Falcon to check out the performance
(same thing Konstantin did for flask).

As for OAuth, it's too bad there's nothing built in, since that's a high
priority thing to get in.

Here's something:
https://github.com/yohanboniface/falcon-oauth
