### ISSUE TITLE
How to use python 3.7 or 3.8 (or latest version) instead of 2. ? [USER ISSUE]

### ISSUE THREAD

**Issue by mellahysf** [codalab/codalab-worksheets#3029]
As described in the title, I want to use python 3.7 or 3.8 (or the latest version) instead of python 2.

How to setup that in the Codalab platform? 

Thanks.

**Comment by yiboliu** [comment]
Hi @mellahysf 

So we currently don't support python 3.7, for the reason [here](https://github.com/codalab/codalab-worksheets/pull/3039). I suggest you to use python 3.6. When you are running python command, use python3.6 rather than python. For example: `python codalab_service.py -> python3.6 codalab_service.py`.
Or a more convenient way would be to set python 3.6 as your default python version. To do that, run `echo "alias python=/usr/local/bin/python3.7" >> ~/.bashrc (or .zshrc, whichever you use)`.

**Comment by yiboliu** [comment]
If you still have questions, feel free to reopen this issue and reach out to me.
