### ISSUE TITLE
Downloaded bundle filename should not be index.html

### ISSUE THREAD

**Issue by kohpangwei** [codalab/codalab-worksheets#3068]
Currently, downloading a bundle from the command line (e.g., ` wget https://worksheets.codalab.org/rest/bundles/0x5b9d528d2101418b87212db92fea6683/contents/blob/`) returns the correct data but in an `index.html` file. This is confusing because the file is actually a .tar.gz file and not .html.

**Comment by epicfaace** [comment]
I'm not sure we can really do much about this, given that `wget` gets the final filename from the URL of the bundle.

Perhaps you would just have to stick with `wget https://worksheets.codalab.org/rest/bundles/0x5b9d528d2101418b87212db92fea6683/contents/blob/ -O blob.tar.gz` for now.

One thing we could do to maybe make this easier is allow people to use `wget https://worksheets.codalab.org/rest/bundles/0x5b9d528d2101418b87212db92fea6683/contents/blob` (without the trailing slash); this way, the downloaded file will be named `blob` rather than `index.html`.
