### ISSUE TITLE
Is it possible to edit the content of a bundle?

### ISSUE THREAD

**Issue by entslscheia** [codalab/codalab-worksheets#3069]
I didn't find an instruction on this everywhere so I suppose it's not supported currently (not entirely sure).
I feel it's necessary to be able to edit the content of an existing bundle. For example, if I am trying to release a dataset and setup a leaderboard using codalab, and I want to make some update of my dataset bundle to fix some small typos, I need to upload a new bundle and then also rebuilding all the downstream bundles depend on the dataset, which is pretty troublesome. I know a way to address this issue is to use `mimic` command, but for my purpose, I prefer not to do this. Directly replacing the content of the original dataset bundle and keep using the same bundle id is something I prefer. So is it feasible at all? Maybe I am missing something here. Any suggestions would be greatly appreciated!

**Comment by epicfaace** [comment]
Hi @entslscheia , unfortunately that is not possible with bundles on CodaLab, because CodaLab is built around bundles being reproducible and immutable. If bundles could be changed after creation, this would break CodaLab's guarantee of immutability and reproducibility. Your best bet is to use `mimic` to create a new bundle from your original bundle.

**Comment by epicfaace** [comment]
You could also look into `cl write` and `cl netcat`, which while they don't do exactly what you're looking for, do you let you communicate with a running bundle.

**Comment by percyliang** [comment]
By design, CodaLab doesn't allow you to mutate existing bundles, just like functional programming doesn't allow you to mutate state.  `cl write` and `cl netcat` only work when the bundle is running.  There is a new `cl upload --link` feature that works with local CodaLab deployments that allow you to point to a mutable location on the filesystem, but this is more for quick and dirty local deployment.

The best thing to do is to use `cl mimic` to rerun all the experiments with the new bundle that you did with the old one.  Because CodaLab tracks provenance, this should in theory be easy (modulo extra compute).

**Comment by entslscheia** [comment]
@epicfaace @percyliang Thanks for your suggestions! They are indeed helpful.
