### ISSUE TITLE
Enforce disk quota before upload starts

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3100]
It would be useful if a user is alerted that they don’t have enough disk quota before the file is uploaded (with `cl upload`), rather than after waiting a long time for the file to upload.

This is especially important if the file is really big, say, tens of GBs, as then the user wastes a lot of time waiting for an upload that then eventually fails.

**Comment by adiprerepa** [comment]
Ideas:

concurrently start upload and checking of disk quota, and if quota exceeded, maybe stop responding on the server (or respond with an error) on that specific upload stream.

Alternatively the server could just respond on the unary quota call. In go we would pass in a context to both threads and then cancel the context if the quota was exceeded.

**Comment by percyliang** [comment]
As a first pass, it might be wise to do a full check before uploading - just to keep things simple instead of fancy threading stuff.  This gives us the opportunity to report the size, number of files, and check the permissions, etc. before uploading begins, and therefore actually have a progress bar with an ETA, which would be cool.  This might be useful anyway since sometimes, it's easy to do a `cl upload` of a directory containing way too many files and a user will now be able to say "whoa, I didn't realize that was 5GB!".

**Comment by adiprerepa** [comment]
do we want to do a full check for uploads of URLs too?

We would probably make a `HEAD` request and check the `Content-Length` header. The nice thing about `HEAD` requests here is that it does not depend on the actual size of the file - so the request would take the same amount of time for 1MB or 100GB.

**Comment by percyliang** [comment]
Don't worry about URLs.  The URL downloading actually happens on the server.
