### ISSUE TITLE
Codalab monitor - extraneous "worker offline" messages

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3161]
Codalab monitor sends us extraneous "worker offline" messages; we don't care that the regular workers are offline, now that we've switched to Azure Batch. We need to change some kind of config to prevent this from happening.

From | <noreply@codalab.org>
-- | --
To | prod-email
Subject | CodaLab on vm-clws-prod-server-0: worker offline [617 times]
Date | Today at 9:17 AM

```
The following public workers are offline:
vm-clws-prod-gpuworker-0
vm-clws-prod-gpuworker-1
vm-clws-prod-gpuworker-9
vm-clws-prod-gpuworker-3
vm-clws-prod-worker-0
vm-clws-prod-gpuworker-8
vm-clws-prod-gpuworker-7
vm-clws-prod-gpuworker-4
vm-clws-prod-gpuworker-2
vm-clws-prod-gpuworker-5
vm-clws-prod-gpuworker-6
vm-clws-prod-worker-1.
```

**Comment by teetone** [comment]
This was already fixed in November in the following PR: https://github.com/codalab/deployment/pull/80/files. The monitor should just log `Environment variable CODALAB_PUBLIC_WORKERS is empty.` instead of sending an email.

This issue will come up if someone restarts or deploys using an old version of the deployment repo.
