### ISSUE TITLE
schema tables are rendering as 'Loading...'

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#3239]
The columns "Exact" and "F1" are just showing "Loading..." forever:
https://worksheets.codalab.org/worksheets/0x816632b5306d41d3ba80ccecc84f1b6e
Javascript console shows a bunch of Forbidden (403) links.  Maybe I'm not supposed to be able to view these bundles?  But then I do have access...  User `pliang`, which is in the `squad` group, which these bundles have given `all` access to.

**Comment by yuqijin** [comment]
@percyliang  Hi Percy, I checked the worksheet and found the issue resulted from the lack of permission. You will be able to view the "Exact" and "F1" columns if logging as the root user, however, since both of these two columns depend on `eval.json`, which is a dependency bundle not belong to the worksheet, you do not have the access to the private bundle.
![image](https://user-images.githubusercontent.com/34461466/107289389-cebab000-6a19-11eb-9527-8e0f557f904e.png)

**Comment by percyliang** [comment]
I see, thanks!  I guess it would be good to show something like 'forbidden' rather than 'Loading...'
