### ISSUE TITLE
Add sentry to CodaLab CLI

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#3536]

**Comment by epicfaace** [comment]
Example of initializing sentry: https://github.com/codalab/codalab-worksheets/blob/d83b8b81e735a6789feda92255654e35311c68ca/codalab/worker/main.py#L248-L249

**Comment by epicfaace** [comment]
@andyjin2000 summarize this discussion and then put it to p3

**Comment by andyjin2000** [comment]
Punting on this issue for now because, although anyone can set up their own codalab server and set up their own CODALAB_SENTRY_INGEST_URL variable, not everyone can set up their own CodaLab CLI (i.e., we publish the CodaLab CLI centrally on pypi and everyone downloads their own CLI). So, if we just set up a single CODALAB_SENTRY_INGEST_URL for the codalab CLI, then everyone who used the codalab CLI would have their data centrally sent to our Sentry account. Not sure if we want to do that due to privacy and other concerns.
