### ISSUE TITLE
Provide default type for schema fields

### ISSUE THREAD

**Issue by yuqijin** [codalab/codalab-worksheets#3599]
For the schemas: time should default to duration, size should default to size

**Comment by jzwang43** [comment]
@yuqijin Can you provided a bit more context on this? I am having some trouble finding where the default types should be defined.

**Comment by epicfaace** [comment]
@jzwang43 the type is defined in the "how to render" column: 
![image](https://user-images.githubusercontent.com/1689183/133518348-6f2717c4-7dc2-4834-bf59-902332ecaacd.png)

See https://codalab-worksheets.readthedocs.io/en/latest/Worksheet-Markdown/#schemas for more information on schema types.

The point of this issue is that if I create a new column in the schema called "time", codalab should just auto-fill the type as "duration" for me for convenience.
