### ISSUE TITLE
can't find python file when executing program

### ISSUE THREAD

**Issue by ManuelSenge** [codalab/codalab-worksheets#3728]
I am new to Codalab. I have one bundle with a python file in it that contains a print statement. When I try to run this python file I get the following error: `python: can't open file 'simple/sort.py': [Errno 2] No such file or directory` even though I added it as a dependency. I used the Web IDE.

**Codalab Information**
- *Your username*: Manuel.Senge
- *UUID of worksheet where problem occurred*: home-Manuel.Senge
- *UUID of problem bundle (please don't delete)*: 0x6325b841318d4251821e5eb53199f21e
- *Error message received from Codalab (if applicable)*: python: can't open file 'simple/sort.py': [Errno 2] No such file or directory
 - *Browser (if on Web)*: Chrome

**To Reproduce**
Steps to reproduce the behavior :
1. execute the python file in the bundle simple

**Expected behavior**
prints out a statement

**Comment by epicfaace** [comment]
@ManuelSenge It looks like your dependency has a folder in it called `simple`, which then contains `sort.py` (see https://worksheets.codalab.org/bundles/0x53341a2188e84847a180565379bf4507). Because your dependency is mounted at the route `simple`, in order to make this work, you should run `python simple/simple/sort.py`.

Let me know if that works!

**Comment by ManuelSenge** [comment]
oh, thank you. I thought the dependency was already the folder. Thank you it works now.
