### ISSUE TITLE
New Worksheet modal dialog: Confirm button should be dark blue 

### ISSUE THREAD

**Issue by jzwang43** [codalab/codalab-worksheets#3832]
This is because it’s the default that gets triggered on enter 
<img width="575" alt="image" src="https://user-images.githubusercontent.com/29891066/137393830-5925b311-b41a-4984-a26f-27b38b704600.png">

**Comment by pranavjain** [comment]
We are using a combination of bootstrap and MUI in our code. This is causing us to have multiple styles overlaps at different places.

I have applied MUI theming on the Confirm button and it looks like below:
![confirm-button](https://user-images.githubusercontent.com/10134824/140186877-d8e65c55-db50-460d-9d60-a15d01f4eddc.png)

Email change button is styled with Bootstrap and it looks like below
![email-change](https://user-images.githubusercontent.com/10134824/140186934-67dbc7d4-4844-4cb0-82e0-e7ede60a0e1b.png)


We should work on unifying our styles so that buttons etc look the same. This might be a big task and will require changes at multiple places.

I am planning to go ahead with this single button change for now.

Comments? @jzwang43 @epicfaace

**Comment by epicfaace** [comment]
I agree with you, Pranav.

--
Ashwin Ramaswami

**Comment by epicfaace** [comment]
Create an issue for this and prioritize (maybe break it up into multiple issues) -- @pranavjain

**Comment by pranavjain** [comment]
> Create an issue for this and prioritize (maybe break it up into multiple issues) -- @pranavjain

Tracking via #3883
