### ISSUE TITLE
make sure bundles in various states behave as expected

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#398]
Currently, if a bundle depends on a killed bundle, it is in the created state forever.

Related: make sure that we can kill / delete bundles in all the various states (even running?).

Bundles should probably time out if they are staged for too long?

In general, make sure the treatment of bundle states is uniform and complete.

**Comment by bkgoksel** [comment]
Server-side timeouts were omitted from Worker 2.0, should be done in the next release.

**Comment by bkgoksel** [comment]
Point 1 fixed in https://github.com/codalab/codalab-cli/pull/930
Point 2 holds true for Preparing and Running. The only unkillable/unremovable state is Finalizing, which now has a fallback to worker offline in https://github.com/codalab/codalab-cli/pull/930

For point 3, what kind of timeout are we thinking? Users can still remove staged bundles. I also wonder whether we should rename staged to `waiting_for_free_worker` or something along those lines so users don't get confused about what they're waiting for.
