### ISSUE TITLE
 Stdout and File Section not working/refreshing

### ISSUE THREAD

**Issue by pranavjain** [codalab/codalab-worksheets#3994]
- User should be able to open the Stddout file and view its content in real time when the job is running.
Bug: The file keeps loading

- Files list take too long to show (refer to 0:45 in the video)
- Stddout output should be printed on the bundle infobox. (Randomly repros, Not visible in the video, visible in the attached screenshot)

https://user-images.githubusercontent.com/10134824/153292800-6e8addb6-6dfc-41f9-92c7-ec5a129176f2.mov

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/10134824/153292790-2fe47a54-463f-438b-8ca8-995ea243b945.png">

**Comment by pranavjain** [comment]
@jzwang43 Please target this one for this week along with the #3989 issue.

Do let me know if you need additional help to repro this bug.

**Comment by pranavjain** [comment]
@epicfaace @teetone Look into this issue

**Comment by jzwang43** [comment]
I think the API that hangs is:

rest/bundles/xxxxx/contents/info/

**Comment by epicfaace** [comment]
The problem is that the frontend keeps requesting this over and over again, even when previous requests are still in progress (so this overloads the server / worker) -- we need to limit it so it only calls the endpoint once the previous calls have succeeded. @jzwang43 can you fix this?

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/1689183/155208765-a86cb5e2-420f-45c8-a003-e35a0d837d0c.png">
