### ISSUE TITLE
[CS324 Instance] Preparing state takes too long

### ISSUE THREAD

**Issue by pranavjain** [codalab/codalab-worksheets#4001]
As per @epicfaace feedback, CodaLab is taking 20+ mins to prepare jobs before running them.

We need to implement caching.

**Comment by epicfaace** [comment]
Ask Michael for a sample bundle

**Comment by pranavjain** [comment]
@epicfaace Were you able to repro this with the bundle Michael gave?

**Comment by epicfaace** [comment]
bundle: https://cs324.codalab.org/bundles/0xaedeeac5452e4b9dab52ed9b02369d89
docker image: https://hub.docker.com/r/sangxie513/cs324-p2-codalab-gpu/tags

**Comment by epicfaace** [comment]
testing: https://cs324.codalab.org/worksheets/0xaf887e97451c419a8a745a5ef5cddc3f

**Comment by epicfaace** [comment]
The problem is that the bundle was requested with a tag `cs324`, and we shouldn't tag bundles when running them on the cs324 instance (since all our workers don't have tags specified). 

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/1689183/154572079-9b9e2220-ca0a-44e6-8c58-73f0ec268fbf.png">

Request bundles without tags, and it should work.

**Comment by pranavjain** [comment]
How does adding a tag increase the time to prepare so long?

**Comment by epicfaace** [comment]
The tag was a different issue -- it was just stuck in staged for a long time.

I removed the tag and am able to reproduce. I'm looking into it

**Comment by epicfaace** [comment]
I think the issue is just that it has to download ~40GB (30GB dependency + 10 GB docker image) which just takes some time to do.

We might be able to make this faster with Tony's PR that solves https://github.com/codalab/codalab-worksheets/issues/3710 -- https://github.com/codalab/codalab-worksheets/pull/3861
