### ISSUE TITLE
Can't download a bundle that was uploaded through bypass upload blob

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#4136]
Try downloading the bundle https://worksheets.codalab.org/bundles/0x7b1273c1eae345c29208330528ecaf3b and it goes to https://storageclwsprod1.blob.core.windows.net/bundles/azfs://devstoreaccount1/bundles/0x7b1273c1eae345c29208330528ecaf3b/contents.gz?se=2022-07-06T15%3A30%3A49Z&sp=rt&sv=2019-12-12&sr=b&rscd=inline%3B%20filename%3D%22_%22&rsce=gzip&rsct=text/plain&sig=qzHzYIr%2Bhl5AnNKlcras171ulhC2BYOrhgHzUbO/bio%3D.

**Comment by wwwjn** [comment]
Do you upload using CLI and try to download using Web browser? @epicfaace

**Comment by epicfaace** [comment]
@wwwjn , I uploaded using the web CLI by doing `cl upload --store blob -c "hello world"`. I tried to download using web browser.

**Comment by wwwjn** [comment]
> @wwwjn , I uploaded using the web CLI by doing `cl upload --store blob -c "hello world"`. I tried to download using web browser.

For now, we only support upload file bypass server, and does not support bypass server for string. So if this is a bug, I think it's not related to bypass server upload.  And I tried upload and download file, it works fine for me.

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/40016222/178092786-8126ec30-68ac-488c-ac01-003b8da30132.png">

**Comment by wwwjn** [comment]
The problem is that bundle storage `blob` points to wrong places ( it points to test Azure account `devstoreaccount1 ` rather than production account). Fix this by delete all this bundle storage and create a new one named `blob-prod`, which points to prod Azure account  `storageclwsprod1 `.
<img width="763" alt="image" src="https://user-images.githubusercontent.com/40016222/179451823-c810762b-9d80-4e82-9d08-e0554d2203ef.png">
