### ISSUE TITLE
takes a long time for jobs to go from created to staged to running

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#415]
Before `cl run date` was basically instantaneous.  Now it's somehow not.

**Comment by sunmeng01** [comment]
I faced the same problem, that a job  has stayed 'staged' for about 3 hours.  How long will the job run from 'staged' status?

**Comment by ghoshs** [comment]
I'm facing the same issue while trying to reproduce executable code. Is there an option to mimic a source code for specific runs? In my current mimic 32 jobs are initiated which have been staged for more than 24 hrs.

**Comment by percyliang** [comment]
The problem is that the mimic also inherits the `--request-queue` flag,
which asks them to be run on specific machines which are not available.
I'd just grab the command (cl info -f args <uuid>) and rerun without the
`--request-queue` flag.

**Comment by ghoshs** [comment]
@percyliang Thanks! The runs are no longer stuck in 'staged'. My runs are however failing with the error 'bash: ./run: Permission denied'. The dashboard shows that I have all permissions on the run file.
I am executing a new run command from a copy of the worksheet (using the wadd command). There are 7 dependencies in the command which I want to run and I have read permissions on all of them.

Do I have to download the dependencies, code and resources from the paper I want to reproduce and upload them in a new worksheet so that I have proper permissions? Or, is there another way?

**Comment by percyliang** [comment]
Try replacing the command with 'bash run ...' instead of './run ...'

**Comment by ghoshs** [comment]
The run still fails with with error triggered within the run script - 
`run: line 1286: warning: here-document at line 8 delimited by end-of-file (wanted `fig/lib')
 run: line 8: $:: command not found`
I'm trying to reproduce the results of [sempre-overnight-acl2015]

**Comment by percyliang** [comment]
Oh, it's a ruby script, so do 'ruby run'

**Comment by percyliang** [comment]
This appears to be an out of memory error.

**Comment by percyliang** [comment]
Closing this because this issue was originally about things being in staged for too long, which is no longer a problem.  Feel free to re-open a separate issue.

**Comment by hscspring** [comment]
it's still take a really long time to run even a very simple cmd (for instance "ls"), 
it's really slow.....
