### ISSUE TITLE
Running codalab in dev mode doesn't work anymore

### ISSUE THREAD

**Issue by epicfaace** [codalab/codalab-worksheets#4429]
Running codalab in dev mode doesn't work anymore (`codalab-service start -bd`). It hangs at the end and then gives an error that the REST API isn't available. I can still run it in non-dev mode though (`codalab-service start -b`).

@wwwjn and I both faced this issue.

**Comment by AndrewJGaut** [comment]
Yeah, I know what this is. I don't know what caused it, though, but basically it happens because the file change event keeps triggering here: https://github.com/codalab/codalab-worksheets/blob/master/codalab/bin/server.py#L32
you can comment out lines 31-33 in that file and then rebuild and it should work.

Not sure what change started triggering that, though.
