### ISSUE TITLE
Application for more space quota.

### ISSUE THREAD

**Issue by rfvscj** [codalab/codalab-worksheets#4439]
I am preparing a task submission which need at least 2G disk space, but there is only only 100M disk quota in the account I register

Could you please increase my disk quota or check the problem why I can only get 100M disk quota? 

Here is the information of my account.
username: zhcren
email: zhcren@outlook.com
uuid:https://worksheets.codalab.org/worksheets/0x1f52a91c6b444ba697b6b00f6df53bac

Thank you in advance.

**Comment by AndrewJGaut** [comment]
Granted!

With regard to why you only got 100M disk quota, right now, non-edu accounts are limited to 100M disk quota and 1 hour time quota because we had crypto miners abusing the free compute we provide. If you sign up with an edu account, you automatically get the old default disk and time quota.

I gave you extra time and disk quota, but please reach out again if needed. Thanks!
