### ISSUE TITLE
stuck in "staged" for long time

### ISSUE THREAD

**Issue by mit10000** [codalab/codalab-worksheets#444]
the bundle keep in staged for long time, never change.
That means all GPUs are being used by others? 
Are there that much jobs running even in early morning?

**Comment by bkgoksel** [comment]
Sometimes runs stay in staged for longer because of other runs as you mentioned, especially when they request GPUs. If you think there's an abnormal waiting time please either include your Codalab username and worksheet/bundle uuid, or better yet send a help ticket from the Codalab UI so we can look into the root cause.

If you have more time-critical jobs, you can `pip install codalabworker` and use the `cl-worker` command to use your own machines as workers on the CodaLab platform (they would be only visible to/used by your bundles). Note that for now you need nvidia-docker (version 1) and nvidia-docker-plugin installed on your machine if you need GPU access.
