### ISSUE TITLE
Specifying multiple hosts with --request-queue fails

### ISSUE THREAD

**Issue by robinjia** [codalab/codalab-worksheets#461]
Using `cl run --request-queue host=X` works if I just specify one host, but it seems to fail if I give a comma-separated list of hosts.  However, this feature is supposedly supported by PBS, so it's unclear why it doesn't work.

For example, doing `cl run 'echo hello' --request-queue host=jagupard8,jagupard11` fails with the failure message: "Failed to launch Torque job: Error allocating memory for add_verify_resources"

**Comment by kashizui** [comment]
This is because this command actually does fail with that same error:
```
qsub -d /tmp -l host=jagupard8,jagupard7 bin/date.sh
```

@robinjia How would you specify multiple hosts on qsub? I'm not able to find documentation

The following command doesn't fail
```
qsub -d /tmp -l host=jagupard8,host=jagupard7 bin/date.sh
```
but not sure if it's actually allowing the job to be scheduled on either node, since it keeps getting scheduled on the second one (even if I switch up the order).

**Comment by robinjia** [comment]
Looks like you want to specify -W x=HOSTLIST:john9,john11, e.g.:

`qsub -q john -W x=HOSTLIST:john9,john11 -I`

FYI I knew it was possible because it's a feature in nlpsub, e.g. try running:

`nlpsub -q john -v -i -H john9,john11`

**Comment by kashizui** [comment]
fix'd
