### ISSUE TITLE
refactor/rename TableBundle, RecordBundle, ...

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#47]
1) Make these share more code - put in one file, perhaps.

2) These should be called TableBlock, RecordBlock, ...

**Comment by andreweduffy** [comment]
I can take a look at this

**Comment by percyliang** [comment]
The naming issue is a bit harrier.  A *raw worksheet item* corresponds to a line in the markdown, a row in the database.  Unfortunately, we've named *interpreted worksheet item* to refer to what we'd like to call blocks - entire tables, where the directives are removed.

So, let's keep the 'item' name and call the different React classes 'TableItem', 'RecordItem', etc.  Don't bother with putting these in the same file.  Just need to rename things.

**Comment by andreweduffy** [comment]
Sorry about the long response time, and Happy (Almost) New Year! I'm currently trying to get my setup back up and running since the repo split, and am running into some friction. Not sure if this was intentional, but it seems like now the website-config.json must include valid SSL config options to make the manage.py `config_gen` task succeed to completion. If that's not the case there's a few ways to fix it by futzing around with the nginx.conf template and setting default values for the SSL options in `settings/__init__.py`.

The second issue is that I get a `TemplateDoesNotExist` error when I try and go to `Browse Templates` through the worksheets page, failing to find `/worksheets/list`. Are these new/am I doing something silly? It seems like the template it's looking for is under `web/worksheets/index.html`, but that file doesn't exist anymore.

**Comment by percyliang** [comment]
On Thu, Dec 31, 2015 at 7:40 PM, Andrew <notifications@github.com> wrote:

> Sorry about the long response time, and Happy (Almost) New Year! I'm
> currently trying to get my setup back up and running since the repo split,
> and am running into some friction. Not sure if this was intentional, but it
> seems like now the website-config.json must include valid SSL config
> options to make the manage.py config_gen task succeed to completion. If
> that's not the case there's a few ways to fix it by futzing around with the
> nginx.conf template and setting default values for the SSL options in
> settings/__init__.py.
>
You don't need to run manage.py config_gen to run things locally (this is
only for using nginx).


> The second issue is that I get a TemplateDoesNotExist error when I try
> and go to Browse Templates through the worksheets page, failing to find
> /worksheets/list. Are these new/am I doing something silly? It seems like
> the template it's looking for is under web/worksheets/index.html, but
> that file doesn't exist anymore.
>
I deleted /worksheets/list.  Now, we have it go to the worksheet 'home'
(which in your case doesn't exist).  So you need to do 'cl new home'.
