### ISSUE TITLE
don't allow docker images without version numbers

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#497]
--request-docker-image ubuntu or ubuntu:latest shouldn't be allowed because this does not nail down a particular docker images.

Of course, these docker images are simply tags, which can get deleted, but at least this is moving in the right direction.

Better yet, maybe should have Dockerfiles be a more essential part of the story.

**Comment by percyliang** [comment]
Figure out whether this is what we want.

**Comment by fabeschan** [comment]
The docker daemon itself can already deal with image digests directly, so specifying --request-docker-image [repo digest] already works (as long as workers have an up-to-date docker installation). We just need to implement a regex filter to make sure we receive a SHA256 string (checking for this in docker_client, on the worker side seems to make the most sense).

The changes required for this is simple but I've been thinking about this a lot... a repo digest is already fairly long. If/when we eventually get our own docker repository up and running, the remote repository path has to be prepended to the repo digest so that makes it even longer. How does this affect ease of use i wonder..

For example, a typical run command can get this long after the changes:
`cl run --request-docker-image codalabtest-on.azurecr.io/ubuntu@sha256:8f5f12335124c1b78e4cf2f8860d395f75ba279bae70a3c18dd470e910e38ec5 :sort.py :a.txt --- python sort.py < a.txt`

**Comment by percyliang** [comment]
Great that it basically works.

We should distinguish `--request-docker-image` and the `docker-image`
that's written down.
- The --request-docker-image can be a tag (even ubuntu:latest), or a
repo+tag or SHA256 or repo+SHA256, and we do whatever we can to resolve the
reference.
- When the worker launches the job though, it should record the SHA256 (and
maybe the repo? though in principle it shouldn't matter).

Then there's the semantics of what it means to rerun something (cl mimic,
or cl info args)...currently I think it just grabs the
--request-docker-image, which isn't guaranteed to work, but in some cases
might be the right behavior (at least might want to propoagate the more
readable --request-docker-image).  Guaranteed reproducibility comes from
putting `docker-image` into the new --request-docker-image, which might be
nice.

**Comment by fabeschan** [comment]
That makes sense, we can have the worker populate the docker-image field when/after the bundle runs.

**Comment by fabeschan** [comment]
https://github.com/codalab/codalab-cli/pull/649 merged. Closing
