### ISSUE TITLE
when scheduling jobs, pay attention to request-memory

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#584]
Currently, worker reports free memory as what's not currently being used.  Instead, it should subtract away the memory that has been requested too via `--request-memory`.

Relevant line:
https://github.com/codalab/codalab-cli/blob/develop/codalab/worker/default_bundle_manager.py#L53

**Comment by kashizui** [comment]
+1 this can be annoying

**Comment by kashizui** [comment]
Also workers should actually report free memory

**Comment by kashizui** [comment]
I just wanted to confirm what the desired behavior should be.. So there are two types of jobs:

- Jobs that don't request memory (let's call them "free-for-all" jobs) have no guarantee for how much memory they will or are allowed to use
- Jobs that do `--request-memory` (let's call them "explicit jobs") should be able to use that much memory on the worker without problems

Should free-for-all jobs and explicit jobs be allowed to coexist on the same worker (and how would that work)? or should a worker that currently has free-for-all jobs only be able to take more free-for-all jobs, while a worker that has explicit jobs can only take more explicit jobs that fit? 


I remember we came up with some trick where each job has an implicit "min" and a "max" requested memory, and using those we could implement a simple allocation algorithm but I don't think I've been able to replicate it exactly.. Something like, free-for-all jobs have `min=0` and `max=infty`, and explicit jobs have `min=max=request_memory`.

**Comment by kashizui** [comment]
I've spent the afternoon thinking about this and I'm not sure what policy exists that could make free-for-all jobs play nice with explicit jobs. Since a free-for-all job is not checked (its memory usage is allowed to increase unbounded until machine goes OOM), scheduling a free-for-all job on the same worker as an explicit job nullifies the memory allocation guarantee for the latter. On the other hand, forcing free-for-all jobs and explicit jobs to be segregated might create resource fragmentation issues: once a machine has been claimed by free-for-all jobs, that machine cannot be used for explicit jobs until it is completely free.

**Comment by kashizui** [comment]
Maybe the best solution is to forget free-for-all jobs completely, and force all unspecified jobs to take on some default request_memory value...

**Comment by fabeschan** [comment]
Hmm, just wondering: what is docker's policy on resource allocation for containers with specified and unspecified resource requirements?

**Comment by percyliang** [comment]
I think it's nice to be able to support free-for-all jobs and explicit
jobs.  I think the point of using the (min, max) formulation is that you
don't even have to think about the free-for-all jobs and explicit jobs
separately - the division just naturally falls out as a special case.

min: guarantee this much memory when a job runs
max: terminate this job when it tries to exceed this amount

Besides explicit (min=max) and free-for-all (min=0, max=infty), we might
have min=1GB, max=3GB too...

+1 to Fabian's point: this is probably a pretty standard scheduling problem
and we should just look around to see what people do.

**Comment by kashizui** [comment]
Hm OK I'm probably overthinking this. I haven't found a standard scheduling problem formulation with min and max constraints, but I was thinking about how the max=infty case throws things off a bit, because if you schedule such a job onto the same worker as other jobs, you essentially void the min-guarantees of the other jobs, since the unbounded job can use up all the memory on the machine unchecked. The solution I guess is to kill that job when it uses more memory than what the worker has left after accounting for memory allocated by the explicit jobs.

**Comment by percyliang** [comment]
Is it bad to just have explicit and free-for-job jobs on separate
machines?  I think this is really just a stop-gap solution that's meant to
be really simple (the only problem we're solving is: if I ask for 10gb, I
should be guaranteed 10gb).  I think moving forward, we want to probably
just use some standard scheduler, especially if we want dynamic scaling of
machines.
