### ISSUE TITLE
Stress testing

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-worksheets#632]
@percyliang:
>  We should probably have a much more aggressive stress test of CodaLab - have 20 jobs all try to bombard it with random things, so we can even run into out of disk failures, etc.

**Comment by fabeschan** [comment]
For stress tests, do we currently have a python layer that sends http requests to the REST server to generate load?

**Comment by kashizui** [comment]
We do not!
Currently we only use the CLI to indirectly make requests to the server.

We do this in two places:

- `codalab-cli/test-cli.py` which is run during CircleCI builds
- `codalab-cli/monitor.py` which runs as a long-lived process alongside deployments to periodically run a few CLI commands against the server to make sure it's still working

@percyliang should stress testing happen in CircleCI or in the monitor?

**Comment by percyliang** [comment]
I don't think we want to stress test things automatically (especially on
the main site), because stress testing should be trying to cause all sorts
of havoc which would destroy performance if not totally crash the system.

Mainly, I think it is used as a tool to unearth bugs that currently just
show up once in a while (the annoying emails that we keep on getting with
things failing, being too slow).

Some things to test:
- upload/download many large files
- run jobs that try to take up all the memory/disk space/hose the network
- create as many bundles as you can on a given worksheet (we don't cap
anything right now, so that's going to be bad)
- create descriptions, names that are very long with weird characters
- have the CLI markdown try to load huge files into tables (we probably
need to truncate things)
- do everything in parallel
- ...

**Comment by fabeschan** [comment]
I agree with @percyliang there, stress tests are meant to run on a cluster that isn't currently servicing production traffic.

**Comment by percyliang** [comment]
I think this is done.
