### ISSUE TITLE
MySQL gone away

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#64]
When MySQL has been inactive for a while (~1 day), then the first bundle service call throws an exception.
http://stackoverflow.com/questions/18054224/python-sqlalchemy-mysql-server-has-gone-away

**Comment by percyliang** [comment]
Fixed by #73 - not

**Comment by kashizui** [comment]
Looking into this now, the solution in a previous project was a major hack: keeping a separate thread to ping the MySQL server every five minutes.

Will look for alternatives...

<facetious>Option B: just get more users so we never time out</facetious>

**Comment by kashizui** [comment]
@percyliang any recommendations for how to test this efficiently? Or at least a machine on which I can test potential solutions and let them sit for a day?

**Comment by percyliang** [comment]
Can we configure MySQL to timeout more frequently?  You could run stuff in
a bunch of docker containers, perhaps too...

**Comment by kashizui** [comment]
After some research, will implement and test the solution provided on pg 32 of this presentation
http://discorporate.us/jek/talks/SQLAlchemy-EuroPython2010.pdf
which looks like a good idea anyway because doing an explicit check of the health of a connection on checkout from the connection pool would (hopefully) guarantee a working connection regardless of the origin of the problem.
