### ISSUE TITLE
support multithreading

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#67]
cl server is currently single-threaded.  Make this multi-threaded so one user doesn't block another.

**Comment by percyliang** [comment]
First attempt in the multithreading branch.  Some weird things happening though.

1) Run two copies of the following:
while true; do cl search size=.sort-; done
The results are non-deterministic.

2) If run one copy of the above and then run ./test-cli.py, then it fails at a random place...

The problem is probably in the treatment of sqlalchemy in bundle_model.py.

**Comment by Raisins** [comment]
I am getting back the correct results while running `while true; do cl search size=.sort-; done` 
Also working fine is running 
`for i in `seq 1 200`; do cl search size=.sort-; done`
in one window while running
`for i in `seq 1 20`; do python test-cli.py upload1; done` 
in another console at the same time is not causing any problems.

What weird results or errors are you seeing.

**Comment by percyliang** [comment]
Try running it for longer - it sometimes takes a few minutes for bad things
to happen.
Make sure you're using mysql with a good number of bundles in the system.
./test-cli.py just crashes, and the 'cl search' command just returns
incorrect results (largest bundle changes in about 10% of the cases).

**Comment by Raisins** [comment]
Made a copy of all the worksheets/bundles on testevn. I have run `cl search ...` across 3 windows and with mysql as the backend. Left it running for 30 min and again for an hour. While I working on worksheets and using them normally as well. I am not seeing any errors or weirdities across both web and cli side.

**Comment by Raisins** [comment]
Make copy of codalab test

**Comment by kashizui** [comment]
Just to confirm, all the existing code is already in codalab/codalab-cli/multithreading branch on github?

**Comment by percyliang** [comment]
Yes

**Comment by kashizui** [comment]
I'm unable to reproduce any errors by running the tests above on the multithreading branch (which i've rebased again)

```
while true; do cl search size=.sort-; done &
while true; do cl search size=.sort-; done &
./test-cli.py all
```

I'm on MySQL, though maybe have at most a dozen bundles on my system at the moment.

**Comment by kashizui** [comment]
Same results after uploading a bunch more bundles.

**Comment by percyliang** [comment]
I'm still getting this issue on Ubuntu 14.04 with MySQL, when I run
the two in different windows:

while true; do cl search size=.sort-; done
while true; do cl search size=.sort-; done

You have to watch it for about 30 seconds before it happens.

I only have 133 bundles of varying size from 4 bytes to 1G.

**Comment by kashizui** [comment]
I'll try again with more bundles (and maybe bigger bundles?).

**Comment by kashizui** [comment]
I've uploaded 110 bundles (ranging from a few bytes to 1.3 GB) and running 

```
while true; do cl search size=.sort-; done
while true; do cl search size=.sort-; done
```

in two different windows in addition to `test-cli.py` for several minutes, still not seeing anything. I am using "MySQLModel" in my config.json.

**Comment by kashizui** [comment]
I'm still unable to reproduce the flickering when running on my system—will try on Digital Ocean, but @percyliang could I bother you to run the test again on a new checkout of the multithreading branch? I pushed (with --force sorry!!) a rebased version of the branch.

**Comment by percyliang** [comment]
Did that.  Problem is still happening for me.

The git hash is:
4d2ad887265cca55ccbf09725823161f8e9095a3

**Comment by kashizui** [comment]
Thank you for testing this—I tried again on Digital Ocean after uploading a bunch of bundles and am still unable to reproduce the flickering. Might there be other things particular to your setup?

**Comment by percyliang** [comment]
Hm, okay, I'll keep on looking.

But independent of this particular issue, can we test the multithreading
and be confident that the logic is sound and that there will be no weird
race conditions?  I'm still worried about two people trying to write to the
same worksheet (or any other form of mutation) and leaving it corrupted.

**Comment by kashizui** [comment]
I'll throw whatever I can at it, and automate it if possible!

**Comment by kashizui** [comment]
Did a deep dive of the SQLAlchemy source code:
- Using Engines directly is the correct way to do things if we are not really using the ORM.
- `Engine.begin()` is thread-safe (connection pool is backed by a custom thread-safe queue)
- All operations on the connection returned by `Engine.begin()` context manager are contained within a `Transaction` with support for automatic commit and rollback
- Connection is automatically `.closed()` on `__exit__`

Conclusions:
- extra calls to `connection.close()` are unnecessary
- transactions ensure that everything within a `with Engine.begin()` context is essentially "atomic"
- any potential race conditions are in our application code, irrelevant to the database operations/connection pooling - I will continue analyzing each of of the CLI calls to check for and address potential race conditions.(Strangely it looks like the `.sort` should not be causing problems, since all of it is essentially building a massive query on a stack before executing it in a transaction.)

**Comment by percyliang** [comment]
Great, thanks!  So the multithreading branch can be simplified a lot then...

**Comment by kashizui** [comment]
I'm going to scope this to addressing the potential problems resulting directly from adding multithreading to `FileServer`---in other words, focusing on issues that only result from multiple threads using the same instances of `LocalBundleClient`, `BundleModel`/`MySQLModel`, and `BundleStore`. I'll create another issue for improperly decoupled actions against the database (e.g. checking if worksheet is frozen and adding an item in separate transactions), since this is a problem regardless of this multithreading patch.

I spent a long time investigating the `cl search size=.sort-` issue in particular, and I honestly can't find any potential reasons for problems—all actions resulting from that command are nondestructive/read-only, and even the select queries are done in batch under single transactions.

`LocalBundleClient` and `BundleModel` do not share any mutable state between threads, so any problems will be at the database level (like those I mentioned above) or at the filesystem level. So I'm moving on to addressing potential `BundleStore`/`FileServer` on the multithreading branch, and recommending that we overlook the `search` flicker issue until it's reproducible.
