### ISSUE TITLE
Workers created with a tag should only accept jobs submitted with that tag

### ISSUE THREAD

**Issue by wooters** [codalab/codalab-worksheets#735]
Currently, if you create a worker with a tag, you can use that tag when you run a job (via the `--request-queue` option) to make sure that the job will run on that worker. However, jobs that are submitted without _any_ tag will also run on the worker.

It would be great if workers created with a tag were "exclusive", so that only jobs that specifically request that tag will run on those workers.

**Comment by maxwang7** [comment]
from Fabian:

@maxwang7 I remember some of us noticing that jobs by default get assigned to whatever worker has the most slots free

[12:16] 
and that ended up assigning cpu jobs to gpu workers because those workers have 6 cores rather than the usual 4

[12:17] 
probably want to change that behavior, while you work on woofer's issue

**Comment by percyliang** [comment]
Fixed with #2117
