### ISSUE TITLE
`wedit` failing on new CLI installation

### ISSUE THREAD

**Issue by maxwang7** [codalab/codalab-worksheets#760]
Reproduce:
- Create a fresh docker container
- `pip install codalab`
- `cl work` --> login
- `cl wedit`
For me, it produced: `OSError: [Errno 2] No such file or directory: '/root/.codalab/misc_temp/tmpxfKrgb.md'`.
When I ran `ls /root/.codalab` I found:
config.json  state.json

codalab/bin/cl.py does try to force creation of the temporary bundle, but it doesn't look like that's happening appropriately.

**Comment by maxwang7** [comment]
Discussed with Stephen, server uses and initializes `~/.codalab/misc_temp` in bundle_sli's server call. We should start using `/tmp/` for clients as the temp directory.

**Comment by percyliang** [comment]
Or just use tempfile to grab the location from wherever the system thinks
is a good location.

Part of the rationale of having it in .codalab was that it was easier to
control where temp files are saved.  If we have big bundles that we need to
create, then we don't want to necessarily stick them in /tmp, which might
fill up the root partition.  But we then created a temp directory for each
partition, and misc_temp because the general temp, which I guess could go
in wherever tempfile is.

If we use tempfile, we should probably just rid of misc_temp completely...
