### ISSUE TITLE
Add a flag to cl rm so that you can kill running bundles and remove them in one go

### ISSUE THREAD

**Issue by kelvinguu** [codalab/codalab-worksheets#78]
Currently, I need to call cl kill first. The killing process takes an uncomfortable 30 seconds or so, during which I repeatedly try calling cl rm until it finally works.

**Comment by percyliang** [comment]
I think the solution is to make cl kill not take 30 seconds.  This is a
known mysterious problem that docker on some machines has this annoying
extra 10 second+ delay.

Combing kill and rm is dangerous since we 'cl kill' can fail due to random
backend reasons (e.g., PBS), and if we rm it, then we might have still have
the processing hang around, which is bad.  Better to have things explicit,
so we're not sweeping things under the rug.

You can also just detach the bundles instead of rm'ing them, and then
removing them all at once:
cl detach <uuid>
cl search .mine .floating -u | xargs cl rm  # be careful with this!

 -Percy

**Comment by kelvinguu** [comment]
Ok, the detach solution sounds good to me.
