### ISSUE TITLE
When defining a schema, provide an option to hide certain rows

### ISSUE THREAD

**Issue by kelvinguu** [codalab/codalab-worksheets#79]
Just a suggested feature:

% schema runs_only
% addschema run
% **hide bundle_type program**

% display table runs_only
[program code]{0xc2803d826c244148b3bd26a6e8a4bc9e}
[run evaluation]{0xa3422744f2f1469c8c7b7a98b5c4f613}
[program code]{0x4a8ff2269dde4aeea88c9a0b9141f9dc}
[run evaluation]{0x1608155ee5894a9d80c96957126f570a}
[program code]{0x0e52113413744396869daa4474adcecd}
...

This can be useful when a user has been in the pattern of:
1. modifying the code, 2. submitting a run, 3. repeat

**Comment by percyliang** [comment]
This definitely would be a nice feature.  We have to think carefully about the best way (syntax) to incorporate this into the directive language, because unlike changing other features of the system, the language is part of the data, which is permanent.  We don't want to have a directive language that evolves in an hacky ad-hoc way.

**Comment by percyliang** [comment]
'hide' should not be part of the schema, which just specifies what fields to display.  Instead, we should have this to filter only runs that have bundle_type.

```
% display table schema1 bundle_type=run
```

In the future, we can support other operations like sorting, showing the latest 5, etc.

**Comment by percyliang** [comment]
Support a general search filter for a table, and then allow specifying a default search filter.

**Comment by percyliang** [comment]
Too complex to support, closing for now.
