### ISSUE TITLE
Migrate to Travis CI

### ISSUE THREAD

**Issue by fabeschan** [codalab/codalab-worksheets#821]
So that our CI tests can use Ubuntu 16.04 and Docker 17.X

**Comment by jder** [comment]
Hey - is this something you're actively working on? I think I have a POC that works locally but seems to still fail on circle. I'd be happy to keep working on this unless you're also working on the same thing.

**Comment by fabeschan** [comment]
We ran into some problems trying to migrate to 2.0. We solved a few but the remaining ones are considered an unbounded time sink; so this has been somewhat de-prioritized. It would be great if you keep working on this!

**Comment by jder** [comment]
Ok, I have a WIP for you folks to look at. It's still failing (including with some new errors) but it at least runs and many tests pass. https://circleci.com/gh/semanticmachines/codalab-cli/10 (based on https://github.com/semanticmachines/codalab-cli/compare/master...semanticmachines:circle-ci-fixes. There are some obvious things that aren't ready to merge in (in particular, the fact that it uses a base image under my dockerhub account).

Do we understand what the current master failures are under circle 1.0? Happy to look into the 2.0 ones but just wanted to make sure it wasn't duplicating effort since many look the same.

**Comment by jder** [comment]
I'm also putting this down for now. Here's the branch where I'm stopping. https://github.com/codalab/codalab-cli/compare/master...semanticmachines:circle-2

For future reference, the main remaining problem is that in Circle CI 2.0, the "remote docker engine" which allows you to run docker containers is isolated from the main process. In particular, you [cannot mount volumes](https://circleci.com/docs/2.0/building-docker-images/#mounting-folders) between the host and the running containers (i.e. we can't mount bundle directories into the jobs). We could potentially work around this as they suggest in that doc by placing the bundle store in a dummy container on the remote engine (rather than on the main host). This might mean also causing upload commands to use `docker cp` or else running the worker itself on the remote engine. (Assuming you can use docker from there...)

**Comment by fabeschan** [comment]
> Do we understand what the current master failures are under circle 1.0?

Yeah that was the case. I've fixed master now to pass tests under circle 1.0

**Comment by fabeschan** [comment]
> We could potentially work around this as they suggest in that doc by placing the bundle store in a dummy container on the remote engine (rather than on the main host).

Wow that looks like something we really don't want to do. Perhaps there's a different CI we can explore instead?

**Comment by fabeschan** [comment]
Migrate to Travis instead. Planning to sunset CircleCI

**Comment by fabeschan** [comment]
Done migrating to Travis
