### ISSUE TITLE
jobs take a long time to go from created to staged to running

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-worksheets#893]
Before, this was just instantaneous.  Now, it takes up to 30 seconds for even simple things like `cl run date`.

**Comment by bkgoksel** [comment]
For bookkeeping, this seems to be a prod-only issue. 
Since prod and dev are running the same version of codalab, this might be slightly annoying to debug, something in our bundle manager iteration is taking considerably longer on prod than dev. My main hunch right now is the number of workers since that's the main difference between prod and dev. Still investigating

**Comment by bkgoksel** [comment]
Looks like this is fixed with the new worker.
