### ISSUE TITLE
`cl upload` doesn't throw an error message when upload bigger than user disk quota

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#912]
Currently the CLI hangs when upload is bigger than user disk quota left, and the upload bundle becomes `failed` with high latency, as reported in [this worksheets issue](https://github.com/codalab/codalab-worksheets/issues/423)

The ideal workflow is to fail the bundle ASAP and also throw an informative error message on the CLI.

**Comment by candicegjing** [comment]
Identical issue #1400 
This issue is fixed. Verified at a local instance, see the following results:
```
stanford@Stanfords-MacBook-Pro codalab-worksheets % time dcl upload scripts
Preparing upload archive...
Uploading scripts.tar.gz (0xd766f7e738cb42c59af460a06f453d1b) to http://rest-server:2900
Sent 0.03MiB [9.85MiB/sec]    			
UsageError: Upload failed: Can't save bundle, bundle size 88954 greater than user's disk quota left: 1.0
docker exec codalab_rest-server_1 cl upload scripts  0.03s user 0.01s system 3% cpu 1.271 total
```
When bundle size exceeds the user disk quota left, the program will print an usageerror without the exception reported in this ticket. The entire process took 0.03s user time, 0.01s system time. No high latency was discovered during testing.
