### ISSUE TITLE
Users with very high disk/time quotas have their runs fail

### ISSUE THREAD

**Issue by bkgoksel** [codalab/codalab-worksheets#973]
Now that we set the `request_disk` and `request_time` of runs to be whatever the user has left in their quota if they don't specify a particular value, if a user has a very high quota, their runs will request very high amounts of disk/time. 

Right now we have global per-bundle maximums and these users will have all their runs fail if their quota is higher than these. If we want to keep these global per-run maximums, we should set the default value to be min(user quota left, per-run maximum). Another solution would be to get rid of per-run maximums.

**Comment by bkgoksel** [comment]
This was merged but left unclosed, closing

**Comment by robinjia** [comment]
I occasionally get errors such as the following:

    Requested more disk (52.0g) than user disk quota left (52.0g)

https://worksheets.codalab.org/bundles/0x79bd024746494ce6b055a644ba05aff3/

If I had to guess, there may be some race condition in which, in between checking the user's remaining quota and requesting that quota, some other running jobs consume more disk.

**Comment by robinjia** [comment]
I still get these errors occasionally, e.g. 0x0028bfa73b5045ab943b8a2261bc472f

In this case, what happened was:
1. I started this job, and it was staged
2. Some other jobs finished
3. This job started running but then failed immediately with this error
4. I reran the exact same command to start this job, and it worked (0x798b3e2429114c4fb705071e4beb1a32)

So it's not that the job itself requires more disk than there is quota available. Seems possibly related to #1285 as well.

**Comment by percyliang** [comment]
Solution: when computing the default amount of disk space to request, if you have X GB left, then request X - 0.5 GB or something like that.

**Comment by candicegjing** [comment]
@robinjia I was just trying to reproduce this issue.  
I created a worksheet [0xfe09997d3ba14a7a88f8aa86e36928ed](https://worksheets.codalab.org/worksheets/0xfe09997d3ba14a7a88f8aa86e36928ed) which only contains all the dependencies for [0x0028bfa73b5045ab943b8a2261bc472f](https://worksheets.codalab.org/bundles/0x0028bfa73b5045ab943b8a2261bc472f). I didn't see the exact error message `Requested more disk (52.0g) than user disk quota left (52.0g)` from the two runs that I created just now, but I do get some error messages as follows:
```
cat: 'data_dir/*.jsonl': No such file or directory
python3.6: can't open file 'src/serve.py': [Errno 2] No such file or directory
python3.6: can't open file 'predict_server.py': [Errno 2] No such file or directory
ls: cannot access 'data_dir/*.jsonl': No such file or directory
```
1. It seems like there is some files missing or permission issues during the run. Do you by any chance know how I could fix them in order to get a successful run? 
2. From the logic inside our job scheduler, it does seem like the jobs were passing from the place where it was originally causing the issue now. So I want to check with you if you still experience a similar problem recently?

**Comment by candicegjing** [comment]
This issue seems to be related to the precision of the disk size's representation. See the following logging message:
```
stanford@Stanfords-MacBook-Pro codalab-worksheets % docker logs codalab_bundle-manager_1 --tail 100
2020-02-20 19:24:24,523 Bundle manager running!
2020-02-20 19:24:31,385 Staging 0x331044f6ab1d468ea7791e2e0c870fca
2020-02-20 19:24:31,408 value = 1126, user_max = 1104.0
2020-02-20 19:24:31,408 Failing 0x331044f6ab1d468ea7791e2e0c870fca: Requested more disk (1.1k) than user disk quota left (1.1k)
```
The final error message doesn't use the same precision as the logic where it does the comparison, see the piece of logic [here](https://github.com/codalab/codalab-worksheets/blob/master/codalab/server/bundle_manager.py#L666). When the program compares the value between user-requested disk space against user's disk quota left, it uses bytes as the unit. However, from the above logging message, both `1126 bytes` and `1104 bytes` are shown as `1.1k` in the final output error message. So it seems reasonable that the bundle failed at this point. 
@percyliang Just want to double-check with you on the final solution: do we want to add more details on the error message (e.g. include the disk quota in bytes) or keep using the original solution?

**Comment by percyliang** [comment]
I think maybe we should improve the error message and show the actual difference, so that it might say "Requested more disk (1.1k) than user disk quota left (1.1k) by 22 bytes".

Also, we should always requesting X - 0.5 GB as I mentioned earlier so this isn't really a problem.
